import path from 'node:path'
import url from 'node:url'

// Subset of npm config type definitions that pnpm actually uses.
// Originally inlined from @pnpm/npm-conf/lib/types.js, trimmed to only
// keys referenced by pnpm commands or passed through to npm-compatible tooling.
export const npmConfigTypes = {
  access: [null, 'restricted', 'public'],
  'allow-same-version': Boolean,
  'bin-links': Boolean,
  ca: [null, String, Array],
  cafile: path,
  cert: [null, String],
  'commit-hooks': Boolean,
  depth: Number,
  description: Boolean,
  dev: Boolean,
  'dry-run': Boolean,
  'engine-strict': Boolean,
  'fetch-retries': Number,
  'fetch-retry-factor': Number,
  'fetch-retry-mintimeout': Number,
  'fetch-retry-maxtimeout': Number,
  force: Boolean,
  git: String,
  'git-tag-version': Boolean,
  global: Boolean,
  'https-proxy': [null, url],
  'ignore-scripts': Boolean,
  'init-author-name': String,
  'init-author-email': String,
  'init-author-url': ['', url],
  'init-license': String,
  'init-version': String,
  json: Boolean,
  key: [null, String],
  'local-address': String,
  long: Boolean,
  maxsockets: Number,
  message: String,
  'node-options': [null, String],
  'node-version': [null, String],
  'no-proxy': [null, String, Array],
  offline: Boolean,
  only: [null, 'dev', 'development', 'prod', 'production'],
  optional: Boolean,
  otp: [null, String],
  'package-lock': Boolean,
  parseable: Boolean,
  'prefer-offline': Boolean,
  prefix: path,
  production: Boolean,
  progress: Boolean,
  provenance: Boolean,
  proxy: [null, false, url],
  registry: [null, url],
  save: Boolean,
  'save-dev': Boolean,
  'save-exact': Boolean,
  'save-optional': Boolean,
  'save-prefix': String,
  'save-prod': Boolean,
  scope: String,
  'script-shell': [null, String],
  'scripts-prepend-node-path': [false, true, 'auto', 'warn-only'],
  'sign-git-tag': Boolean,
  'strict-ssl': Boolean,
  tag: String,
  'tag-version-prefix': String,
  'unsafe-perm': Boolean,
  'user-agent': String,
  userconfig: path,
  umask: Number,
  version: Boolean,
}
