export { selfUpdate } from './self-updater/index.js'
export { assertPnpmRuns, assertReleaseIsInstallable, exePlatformPkgDirName, exePlatformPkgDirNameNext, installPnpm, installPnpmToStore, isReleaseInstallable, linkExePlatformBinary, pnpmPackageNameToInstall } from './self-updater/installPnpm.js'
export { type PnpmVersionLookup, prepareResolvePnpmVersion, type ResolvedPnpmVersion, resolvePnpmVersion, type ResolvePnpmVersionOptions } from './self-updater/resolvePnpmVersion.js'
export { verifyPnpmEngineIdentity, type VerifyPnpmEngineIdentityOptions } from './self-updater/verifyPnpmEngineIdentity.js'
export { setup } from './setup/index.js'
export { LEGACY_HOME_DIR_SHIM_NAMES } from './setup/setup.js'
export { withCmd } from './with/index.js'
