export { selfUpdate } from './self-updater/index.js'
export { assertPnpmRuns, assertReleaseIsInstallable, exePlatformPkgDirName, exePlatformPkgDirNameNext, installPnpm, installPnpmToStore, isReleaseInstallable, linkExePlatformBinary, nativeTargetName, pnpmPackageNameToInstall } from './self-updater/installPnpm.js'
export { type PnpmVersionLookup, prepareResolvePnpmVersion, type ResolvedPnpmVersion, resolvePnpmVersion, type ResolvePnpmVersionOptions } from './self-updater/resolvePnpmVersion.js'
export { type PnpmEngineToVerify, verifyPnpmEngineIdentity, type VerifyPnpmEngineIdentityOptions } from './self-updater/verifyPnpmEngineIdentity.js'
export { setup } from './setup/index.js'
export { LEGACY_HOME_DIR_SHIM_NAMES, legacyGlobalAddSpecs } from './setup/setup.js'
export { spawnPnpm, type SpawnPnpmResult } from './spawnPnpm.js'
export { withCmd } from './with/index.js'
