# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  "pacquet/crates/crypto-shasums-file/src/node_release_keys.rs",
]

[default.extend-words]
cafs = "cafs"
ect  = "ect"
pn   = "pn"

[default.extend-identifiers]
PnP = "PnP"
