import eslintConfig, { sizeAndShapeRules } from "@pnpm/eslint-config";
import * as regexpPlugin from "eslint-plugin-regexp";

// Packages whose code still exceeds the size and shape limits. Remove a
// package from this list once it is refactored to pass them.
const PENDING_SIZE_AND_SHAPE_REFACTOR = [
    ".meta-updater/**",
    "pnpm11/__utils__/assert-store/**",
    "pnpm11/__utils__/scripts/**",
    "pnpm11/__utils__/test-fixtures/**",
    "pnpm11/auth/commands/**",
    "pnpm11/bins/cmd-shim/**",
    "pnpm11/bins/linker/**",
    "pnpm11/bins/resolver/**",
    "pnpm11/building/after-install/**",
    "pnpm11/building/commands/**",
    "pnpm11/building/during-install/**",
    "pnpm11/cache/commands/**",
    "pnpm11/catalogs/config/**",
    "pnpm11/cli/parse-cli-args/**",
    "pnpm11/config/commands/**",
    "pnpm11/config/normalize-registries/**",
    "pnpm11/config/package-is-installable/**",
    "pnpm11/config/version-policy/**",
    "pnpm11/core/error/**",
    "pnpm11/deps/compliance/audit/**",
    "pnpm11/deps/compliance/license-scanner/**",
    "pnpm11/deps/compliance/sbom/**",
    "pnpm11/deps/github-actions/**",
    "pnpm11/deps/graph-builder/**",
    "pnpm11/deps/graph-hasher/**",
    "pnpm11/deps/graph-sequencer/**",
    "pnpm11/deps/inspection/list/**",
    "pnpm11/deps/inspection/outdated/**",
    "pnpm11/deps/inspection/peers-checker/**",
    "pnpm11/deps/path/**",
    "pnpm11/deps/peer-range/**",
    "pnpm11/deps/security/signatures/**",
    "pnpm11/deps/status/**",
    "pnpm11/engine/pm/commands/**",
    "pnpm11/engine/runtime/bun-resolver/**",
    "pnpm11/engine/runtime/commands/**",
    "pnpm11/engine/runtime/deno-resolver/**",
    "pnpm11/engine/runtime/node-resolver/**",
    "pnpm11/exec/lifecycle/**",
    "pnpm11/exec/prepare-package/**",
    "pnpm11/fetching/binary-fetcher/**",
    "pnpm11/fetching/directory-fetcher/**",
    "pnpm11/fetching/git-fetcher/**",
    "pnpm11/fetching/pick-fetcher/**",
    "pnpm11/fetching/tarball-fetcher/**",
    "pnpm11/fs/dir-lock/**",
    "pnpm11/fs/graceful-fs/**",
    "pnpm11/fs/hard-link-dir/**",
    "pnpm11/fs/indexed-pkg-importer/**",
    "pnpm11/fs/packlist/**",
    "pnpm11/fs/read-modules-dir/**",
    "pnpm11/global/commands/**",
    "pnpm11/global/packages/**",
    "pnpm11/hooks/pnpmfile/**",
    "pnpm11/hooks/read-package-hook/**",
    "pnpm11/installing/commands/**",
    "pnpm11/installing/context/**",
    "pnpm11/installing/deps-installer/**",
    "pnpm11/installing/deps-resolver/**",
    "pnpm11/installing/linking/direct-dep-linker/**",
    "pnpm11/installing/linking/hoist/**",
    "pnpm11/installing/linking/modules-cleaner/**",
    "pnpm11/installing/linking/real-hoist/**",
    "pnpm11/installing/modules-yaml/**",
    "pnpm11/installing/package-requester/**",
    "pnpm11/lockfile/detect-dep-types/**",
    "pnpm11/lockfile/filtering/**",
    "pnpm11/lockfile/fs/**",
    "pnpm11/lockfile/make-dedicated-lockfile/**",
    "pnpm11/lockfile/merger/**",
    "pnpm11/lockfile/peer-edges/**",
    "pnpm11/lockfile/preferred-versions/**",
    "pnpm11/lockfile/pruner/**",
    "pnpm11/lockfile/settings-checker/**",
    "pnpm11/lockfile/utils/**",
    "pnpm11/lockfile/verification/**",
    "pnpm11/lockfile/walker/**",
    "pnpm11/modules-mounter/daemon/**",
    "pnpm11/network/agent/**",
    "pnpm11/network/auth-header/**",
    "pnpm11/network/web-auth/**",
    "pnpm11/object/property-path/**",
    "pnpm11/os/env/path-extender-posix/**",
    "pnpm11/patching/apply-patch/**",
    "pnpm11/patching/commands/**",
    "pnpm11/patching/config/**",
    "pnpm11/pkg-manifest/commands/**",
    "pnpm11/pkg-manifest/utils/**",
    "pnpm11/registry-access/commands/**",
    "pnpm11/releasing/exportable-manifest/**",
    "pnpm11/resolving/default-resolver/**",
    "pnpm11/resolving/git-resolver/**",
    "pnpm11/resolving/local-resolver/**",
    "pnpm11/resolving/registry/pkg-metadata-filter/**",
    "pnpm11/store/cafs/**",
    "pnpm11/store/commands/**",
    "pnpm11/store/connection-manager/**",
    "pnpm11/store/controller/**",
    "pnpm11/store/file-mode/**",
    "pnpm11/store/index/**",
    "pnpm11/testing/registry-mock/**",
    "pnpm11/text/comments-parser/**",
    "pnpm11/text/tree-renderer/**",
    "pnpm11/workspace/commands/**",
    "pnpm11/workspace/injected-deps-syncer/**",
    "pnpm11/workspace/project-manifest-reader/**",
    "pnpm11/workspace/projects-filter/**",
    "pnpm11/workspace/projects-graph/**",
    "pnpm11/workspace/projects-reader/**",
    "pnpm11/workspace/task-scheduler/**",
    "pnpm11/workspace/workspace-manifest-reader/**",
    "pnpm11/yaml/document-sync/**",
]

export default [
    {
        ignores: ["**/fixtures", "**/__fixtures__", "**/node_modules", "**/lib", ".claude/**", "bench-work-env/**"],
    },
    ...eslintConfig,
    regexpPlugin.configs['flat/recommended'],
    {
        files: ["pnpm11/pnpm/src/**/*.ts"],
        rules: {
            "import-x/no-extraneous-dependencies": "off",
        },
    },
    {
        files: PENDING_SIZE_AND_SHAPE_REFACTOR,
        rules: Object.fromEntries(
            Object.keys(sizeAndShapeRules)
                .filter((rule) => rule !== "perfectionist/overly-complex-condition" && rule !== "perfectionist/overly-long-method-chain")
                .map((rule) => [rule, "off"])
        ),
    },
]
