scripts:
  test: >-
    pnpm run build &&
    pnpm recursive test
    --reporter=append-only
    --workspace-concurrency=1
    --filter=./packages
    --filter=./privatePackages
  build: pnpm recursive run tsc
devDependencies:
  '@pnpm/tsconfig': 'link:utils/tsconfig'
  '@pnpm/tslint-config': 'link:utils/tslint-config'
  '@types/node': '*'
  '@types/tape': ^4.2.31
  ts-node: 8.3.0
  tslint: 5.19.0
  typescript: 3.6.2
engines:
  pnpm: '>=3.7'
