packages:
  - cli/*
  - config/*
  - env/*
  - exec/*
  - fetching/*
  - fs/*
  - lockfile/*
  - network/*
  - hooks/*
  - pkg-manager/*
  - pkg-manifest/*
  - resolving/*
  - reviewing/*
  - store/*
  - workspace/*
  - packages/*
  - packages/artifacts/*
  - privatePackages/*
  - typings
  - .meta-updater
  - utils/*
  - "!**/__package_previews__/**"
  - "!**/example/**"
  - "!**/test/**"
  - "!packages/local-resolver/example-package/**"
