packages:
  - .meta-updater
  - __typings__
  - __utils__/*
  - "!__utils__/build-artifacts"
  - catalogs/*
  - cli/*
  - completion/*
  - config/*
  - crypto/*
  - dedupe/*
  - deps/*
  - env/*
  - exec/*
  - fetching/*
  - fs/*
  - hooks/*
  - lockfile/*
  - network/*
  - modules-mounter/*
  - packages/*
  - pkg-manager/*
  - pkg-manifest/*
  - patching/*
  - pnpm
  - worker
  - pnpm/artifacts/*
  - releasing/*
  - resolving/*
  - reviewing/*
  - store/*
  - text/*
  - workspace/*
  - "!**/example/**"
  - "!**/test/**"
  - "!resolving/local-resolver/example-package/**"
catalog:
  "@pnpm/registry-mock": 3.32.1
  "@types/ramda": 0.29.12
  "@types/semver": 7.5.3
  "@types/is-windows": ^1.0.2
  "@zkochan/rimraf": ^2.1.3
  p-filter: ^2.1.0
  p-limit: ^3.1.0
  ramda: npm:@pnpm/ramda@0.28.1
  semver: ^7.6.2
  sinon: ^16.1.3
  symlink-dir: ^6.0.0
  is-windows: ^1.0.2
  nock: 13.3.4
  write-json-file: ^4.3.0
  write-yaml-file: ^5.0.0
  execa: npm:safe-execa@0.1.2
  which: npm:@pnpm/which@^3.0.1
  render-help: ^1.0.3
  read-yaml-file: ^2.1.0
  load-json-file: ^6.2.0
  is-subdir: ^1.2.0
  sort-keys: ^4.2.0
  normalize-path: ^3.0.0
  run-groups: ^3.0.1
  version-selector-type: ^3.0.0
