packages:
  - .meta-updater
  - __typings__
  - __utils__/*
  - cli/*
  - config/*
  - env/*
  - exec/*
  - fetching/*
  - fs/*
  - hooks/*
  - lockfile/*
  - network/*
  - packages/*
  - pkg-manager/*
  - pkg-manifest/*
  - pnpm
  - pnpm/artifacts/*
  - releasing/*
  - resolving/*
  - reviewing/*
  - store/*
  - text/*
  - workspace/*
  - "!**/example/**"
  - "!**/test/**"
  - "!resolving/local-resolver/example-package/**"
