packages:
  - packages/*
  - privatePackages/*
  - typings
  - tools
  - utils/*
  - "!**/__package_previews__/**"
  - "!**/example/**"
  - "!**/test/**"
  - "!packages/local-resolver/example-package/**"
  - "!packages/dependencies-hierarchy/fixtures/**"
  - "!packages/dependencies-hierarchy/fixtureMonorepo/**"
  - "!packages/dependencies-hierarchy/fixtureWithLinks/**"
  - "!privatePackages/test-fixtures/fixtures/**"
