packages:
  - .meta-updater
  - __typecheck__
  - __typings__
  - __utils__/*
  - '!__utils__/build-artifacts'
  - builder/*
  - cache/*
  - catalogs/*
  - cli/*
  - completion/*
  - config/*
  - crypto/*
  - dedupe/*
  - deps/*
  - env/*
  - exec/*
  - fetching/*
  - fs/*
  - global/*
  - hooks/*
  - lockfile/*
  - network/*
  - modules-mounter/*
  - object/*
  - packages/*
  - pkg-manager/*
  - pkg-manifest/*
  - patching/*
  - pnpm
  - pnpm/dev
  - testing/*
  - tools/*
  - worker
  - pnpm/artifacts/*
  - registry/*
  - releasing/*
  - resolving/*
  - reviewing/*
  - semver/*
  - store/*
  - text/*
  - workspace/*
  - yaml/*
  - '!**/example/**'
  - '!**/test/**'
  - '!resolving/local-resolver/example-package/**'

allowBuilds:
  core-js: false
  esbuild: true
  fuse-native: true
  ghooks: true
  msgpackr-extract: true
  unrs-resolver: true

auditConfig:
  ignoreCves:
    - CVE-2025-56200
  ignoreGhsas:
    - GHSA-2g4f-4pwh-qvx6
    - GHSA-76c9-3jph-rj3q
    - GHSA-ffrw-9mx8-89p8
    - GHSA-mh29-5h37-fv8m

catalog:
  '@babel/core': ^7.28.3
  '@babel/plugin-transform-explicit-resource-management': ^7.27.1
  '@changesets/cli': ^2.29.8
  '@commitlint/cli': ^20.4.1
  '@commitlint/config-conventional': ^20.4.1
  '@commitlint/prompt-cli': ^20.4.1
  '@cyclonedx/cyclonedx-library': 9.4.1
  '@eslint/js': ^9.18.0
  '@jest/globals': 30.0.5
  '@npm/types': ^2.1.0
  '@pnpm/byline': ^1.0.0
  '@pnpm/colorize-semver-diff': ^1.0.1
  '@pnpm/config.env-replace': ^3.0.2
  '@pnpm/config.nerf-dart': ^1.0.0
  '@pnpm/exec': ^2.0.0
  '@pnpm/log.group': 3.0.1
  '@pnpm/logger': '>=1001.0.0 <1002.0.0'
  '@pnpm/meta-updater': 2.0.6
  '@pnpm/network.agent': ^2.0.3
  '@pnpm/nopt': ^0.3.1
  '@pnpm/npm-conf': 3.0.2
  '@pnpm/npm-lifecycle': ^1001.0.0
  '@pnpm/npm-package-arg': ^2.0.0
  '@pnpm/os.env.path-extender': ^2.0.3
  '@pnpm/patch-package': 0.0.1
  '@pnpm/registry-mock': 5.2.1
  '@pnpm/semver-diff': ^1.1.0
  '@pnpm/tabtab': ^0.5.4
  '@pnpm/tgz-fixtures': 0.0.0
  '@pnpm/util.lex-comparator': ^3.0.2
  '@pnpm/workspace.find-packages': ^1000.0.15
  '@pnpm/workspace.read-manifest': ^1000.1.1
  '@reflink/reflink': 0.1.19
  '@rushstack/worker-pool': 0.7.1
  '@stylistic/eslint-plugin': ^4.4.1
  '@types/adm-zip': ^0.5.7
  '@types/archy': 0.0.36
  '@types/cross-spawn': ^6.0.6
  '@types/fs-extra': ^9.0.13
  '@types/graceful-fs': ^4.1.9
  '@types/hosted-git-info': ^3.0.5
  '@types/ini': 1.3.31
  '@types/is-gzip': 2.0.0
  '@types/is-windows': ^1.0.2
  '@types/isexe': 2.0.2
  '@types/jest': ^30.0.0
  '@types/js-yaml': ^4.0.9
  '@types/libnpmpublish': ^9.0.1
  '@types/lodash.kebabcase': 4.1.9
  '@types/lodash.throttle': 4.1.7
  '@types/micromatch': ^4.0.9
  '@types/node': ^22.19.11
  '@types/normalize-package-data': ^2.4.4
  '@types/normalize-path': ^3.0.2
  '@types/object-hash': 3.0.6
  '@types/parse-json': ^4.0.2
  '@types/picomatch': ^4.0.2
  '@types/pnpm__byline': npm:@types/byline@^4.2.36
  '@types/proxyquire': ^1.3.31
  '@types/ramda': 0.29.12
  '@types/retry': ^0.12.5
  '@types/semver': 7.7.1
  '@types/sinon': ^10.0.20
  '@types/ssri': ^7.1.5
  '@types/tar': ^6.1.13
  '@types/tar-stream': ^2.2.3
  '@types/touch': ^3.1.5
  '@types/validate-npm-package-name': ^4.0.2
  '@types/which': ^2.0.2
  '@types/write-file-atomic': ^4.0.3
  '@types/yarnpkg__lockfile': ^1.1.9
  '@types/zkochan__table': npm:@types/table@6.0.0
  '@typescript-eslint/utils': ^8.53.0
  '@typescript/native-preview': 7.0.0-dev.20260216.1
  '@yarnpkg/core': 4.2.0
  '@yarnpkg/extensions': 2.0.3
  '@yarnpkg/lockfile': ^1.1.0
  '@yarnpkg/nm': 4.0.5
  '@yarnpkg/parsers': 3.0.3
  '@yarnpkg/pnp': ^4.0.8
  '@zkochan/cmd-shim': ^8.0.1
  '@zkochan/retry': ^0.2.0
  '@zkochan/rimraf': ^3.0.2
  '@zkochan/table': ^2.0.1
  adm-zip: ^0.5.16
  ansi-diff: ^1.2.0
  archy: ^1.0.0
  better-path-resolve: 1.0.0
  bin-links: ^5.0.0
  bole: ^5.0.17
  boxen: npm:@zkochan/boxen@5.1.2
  c8: ^7.14.0
  camelcase: ^9.0.0
  camelcase-keys: ^10.0.1
  can-link: ^2.0.0
  can-write-to-dir: ^1.1.1
  chalk: ^5.6.0
  ci-info: ^4.3.0
  cli-columns: ^4.0.0
  cli-truncate: ^4.0.0
  cmd-extension: ^1.0.2
  comver-to-semver: ^1.0.0
  concurrently: 9.2.1
  cross-env: ^10.1.0
  cross-spawn: ^7.0.6
  cspell: 9.2.0
  deep-require-cwd: 1.0.0
  delay: ^6.0.0
  detect-indent: 7.0.1
  detect-libc: ^2.0.3
  didyoumean2: ^7.0.4
  dint: ^5.1.0
  dir-is-case-sensitive: ^2.0.0
  encode-registry: ^3.0.1
  enquirer: ^2.4.1
  esbuild: ^0.25.9
  escape-string-regexp: ^5.0.0
  eslint: ^9.39.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jest: ^29.12.1
  eslint-plugin-n: ^17.23.2
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-regexp: ^2.10.0
  execa: npm:safe-execa@0.2.0
  exists-link: 2.0.0
  fast-deep-equal: ^3.1.3
  fast-glob: ^3.3.3
  filenamify: ^6.0.0
  find-up: ^7.0.0
  fs-extra: ^11.3.1
  fuse-native: ^2.2.6
  get-npm-tarball-url: ^2.1.0
  get-port: ^7.1.0
  ghooks: 2.0.4
  graceful-fs: ^4.2.11
  graceful-git: ^4.0.0
  graph-cycles: 3.0.0
  hosted-git-info: npm:@pnpm/hosted-git-info@1.0.0
  https-proxy-server-express: 0.1.2
  husky: ^9.1.7
  hyperdrive-schemas: ^2.0.0
  ini: 6.0.0
  is-gzip: 2.0.0
  is-inner-link: ^4.0.0
  is-subdir: ^1.2.0
  is-windows: ^1.0.2
  isexe: 2.0.0
  jest: ^30.2.0
  jest-diff: ^30.1.1
  js-yaml: npm:@zkochan/js-yaml@0.0.11
  json5: ^2.2.3
  keyv: 4.5.4
  lcov-result-merger: ^3.3.0
  libnpmpublish: ^11.1.3
  load-json-file: ^7.0.1
  lodash.kebabcase: ^4.1.1
  lodash.throttle: 4.1.1
  loud-rejection: ^2.2.0
  lru-cache: ^11.1.0
  make-empty-dir: ^3.0.2
  mdast-util-to-string: ^2.0.0
  memoize: ^10.2.0
  micromatch: ^4.0.8
  msgpackr: ^1.11.2
  nm-prune: ^5.0.0
  nock: 13.3.4
  node-fetch: ^3.3.2
  normalize-newline: 4.1.0
  normalize-package-data: ^8.0.0
  normalize-path: ^3.0.0
  normalize-registry-url: 2.0.1
  npm-packlist: 10.0.3
  object-hash: 3.0.0
  p-defer: ^4.0.1
  p-every: ^2.0.0
  p-filter: ^4.1.0
  p-limit: ^7.1.0
  p-map-values: ^1.0.0
  p-memoize: 8.0.0
  p-queue: ^8.1.0
  parse-json: ^8.3.0
  parse-npm-tarball-url: ^4.0.0
  path-absolute: ^1.0.1
  path-exists: ^5.0.0
  path-name: ^1.0.0
  path-temp: ^2.1.1
  pidtree: ^0.6.0
  preferred-pm: ^3.1.4
  pretty-bytes: ^7.0.1
  pretty-ms: ^9.2.0
  promise-share: ^1.0.0
  proxyquire: ^2.1.3
  ps-list: ^8.1.1
  ramda: npm:@pnpm/ramda@0.28.1
  read-ini-file: 4.0.0
  read-yaml-file: ^2.1.0
  realpath-missing: ^1.1.0
  remark-parse: ^9.0.0
  remark-stringify: ^9.0.1
  rename-overwrite: ^6.0.2
  render-help: ^1.0.3
  resolve-link-target: ^2.0.0
  rimraf: ^6.1.2
  root-link-target: ^3.1.0
  run-groups: ^4.0.0
  rxjs: ^7.8.2
  safe-buffer: 5.2.1
  safe-execa: ^0.2.0
  safe-promise-defer: ^1.0.1
  sanitize-filename: ^1.6.3
  semver: ^7.7.2
  semver-range-intersect: ^0.3.1
  semver-utils: ^1.1.4
  shlex: ^3.0.0
  shx: ^0.4.0
  sinon: ^16.1.3
  sort-keys: ^6.0.0
  split-cmd: ^1.1.0
  split2: ^4.2.0
  ssri: 13.0.0
  stacktracey: ^2.1.8
  string-length: ^6.0.0
  strip-bom: ^5.0.0
  strip-comments-strings: 1.2.0
  symlink-dir: ^7.0.0
  tar: ^7.5.7
  tar-stream: ^3.1.7
  tempy: 3.0.0
  terminal-link: ^4.0.0
  tinyglobby: ^0.2.14
  touch: 3.1.0
  tree-kill: ^1.2.2
  ts-jest-resolver: 2.0.1
  typescript: 5.9.2
  typescript-eslint: ^8.53.0
  unified: ^9.2.2
  validate-npm-package-name: 7.0.2
  verdaccio: 6.2.7
  version-selector-type: ^3.0.0
  which: npm:@pnpm/which@^3.0.1
  write-file-atomic: ^7.0.0
  write-ini-file: 4.0.1
  write-json-file: ^7.0.0
  write-json5-file: ^3.1.0
  write-package: 7.2.0
  write-yaml-file: ^5.0.0
  yaml: ^2.8.1
  yaml-tag: 1.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

enableGlobalVirtualStore: true

enablePrePostScripts: false

engineStrict: true

gitChecks: false

hoistPattern:
  - jest-runner

managePackageManagerVersions: true

minimumReleaseAge: 1440 # At least a day

minimumReleaseAgeExclude:
  - '@pnpm/*'
  - '@rushstack/worker-pool@0.7.1'
  - '@zkochan/cmd-shim@8.0.0 || 8.0.1'
  - body-parser@2.2.1
  - express@4.22.1
  - glob@11.1.0
  - jws@3.2.3
  - normalize-registry-url
  - path-temp@2.1.1
  - parse-npm-tarball-url@4.0.0
  - pnpm
  - run-groups@4.0.0
  - tar@7.5.7
  - lodash@4.17.23
  - qs@6.14.2

nodeVersion: 22.13.0

optimisticRepeatInstall: true

overrides:
  '@cypress/request@3.0.9>qs': ^6.14.1
  '@yarnpkg/fslib@2': '3'
  body-parser@<2.2.1: '^2.2.1'
  clipanion: 3.2.0-rc.6
  cookie@<0.7.0: '>=0.7.0'
  cross-spawn@<7.0.5: '>=7.0.5'
  debug@<3.1.0: '>=3.1.0'
  diff@<8.0.3: '^8.0.3'
  express@<4.22.1: ^4.22.1
  follow-redirects@<=1.15.5: '>=1.15.6'
  glob-parent@<5.1.2: '>=5.1.2'
  glob@>=10.3.7 <=11.0.3: '^11.1.0'
  hosted-git-info@1: 'catalog:'
  http-proxy-middleware@<2.0.7: ^2.0.7
  istanbul-reports: npm:@zkochan/istanbul-reports
  js-yaml@<3.14.2: '^3.14.2'
  js-yaml@^4.0.0: 'catalog:'
  json5@<2.2.2: 'catalog:'
  jsonwebtoken@<=8.5.1: '>=9.0.0'
  jws@<3.2.3: '^3.2.3'
  lodash@>=4.0.0 <=4.17.22: '^4.17.23'
  minimatch@>=7.0.0 <7.4.7: '^7.4.7'
  nopt@5: npm:@pnpm/nopt@^0.2.1
  on-headers@<1.1.0: '>=1.1.0'
  path-to-regexp@<0.1.12: ^0.1.12
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  path-to-regexp@>=7.0.0 <8.0.0: '>=8.0.0'
  postman-request>qs: ^6.14.1
  request: npm:postman-request@2.88.1-postman.40
  semver@<7.5.2: 'catalog:'
  send@<0.19.0: ^0.19.0
  serve-static@<1.16.0: ^1.16.0
  socks@2: ^2.8.1
  tar@<=7.5.6: '>=7.5.7'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  validator@<13.15.22: '>=13.15.22'
  yaml@<2.2.2: '>=2.2.2'

packageExtensions:
  '@babel/parser':
    peerDependencies:
      '@babel/types': '*'
  '@verdaccio/auth':
    peerDependencies:
      express: '*'
  jest-circus:
    dependencies:
      slash: '3'
  remark-parse:
    peerDependencies:
      unified: '*'
  remark-stringify:
    peerDependencies:
      unified: '*'

patchedDependencies:
  '@pnpm/npm-lifecycle': __patches__/@pnpm__npm-lifecycle.patch
  graceful-fs@4.2.11: __patches__/graceful-fs@4.2.11.patch
  mdast-util-to-string@2.0.0: __patches__/mdast-util-to-string@2.0.0.patch

patchesDir: __patches__

publishBranch: main

resolutionMode: lowest-direct

savePrefix: ''

sharedWorkspaceLockfile: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@yarnpkg/libzip@3.2.2'
  - rxjs@7.8.2
  - undici-types@6.21.0
  - '@pnpm/*'

trustPolicyIgnoreAfter: 10080 # 1 week

verifyDepsBeforeRun: install
