packages:
  - packages/*
  - packages/artifacts/*
  - privatePackages/*
  - typings
  - .meta-updater
  - utils/*
  - "!**/__package_previews__/**"
  - "!**/example/**"
  - "!**/test/**"
  - "!packages/local-resolver/example-package/**"
