packages:
  - .meta-updater
  - __typings__
  - __utils__/*
  - "!__utils__/build-artifacts"
  - catalogs/*
  - cli/*
  - completion/*
  - config/*
  - crypto/*
  - dedupe/*
  - deps/*
  - env/*
  - exec/*
  - fetching/*
  - fs/*
  - hooks/*
  - lockfile/*
  - network/*
  - modules-mounter/*
  - packages/*
  - pkg-manager/*
  - pkg-manifest/*
  - patching/*
  - pnpm
  - worker
  - pnpm/artifacts/*
  - releasing/*
  - resolving/*
  - reviewing/*
  - store/*
  - text/*
  - workspace/*
  - "!**/example/**"
  - "!**/test/**"
  - "!resolving/local-resolver/example-package/**"
catalog:
  "@pnpm/registry-mock": 3.32.1
  "@types/ramda": 0.29.12
  "@types/semver": 7.5.3
  ramda: npm:@pnpm/ramda@0.28.1
  semver: ^7.6.2
