packages:
  - .meta-updater
  - __typings__
  - __utils__/*
  - "!__utils__/build-artifacts"
  - catalogs/*
  - cli/*
  - completion/*
  - config/*
  - crypto/*
  - dedupe/*
  - deps/*
  - env/*
  - exec/*
  - fetching/*
  - fs/*
  - hooks/*
  - lockfile/*
  - network/*
  - modules-mounter/*
  - packages/*
  - pkg-manager/*
  - pkg-manifest/*
  - patching/*
  - pnpm
  - worker
  - pnpm/artifacts/*
  - releasing/*
  - resolving/*
  - reviewing/*
  - store/*
  - text/*
  - workspace/*
  - "!**/example/**"
  - "!**/test/**"
  - "!resolving/local-resolver/example-package/**"
catalog:
  "@pnpm/builder.policy": 3.0.0
  "@pnpm/registry-mock": 3.32.1
  "@types/fs-extra": ^9.0.13
  "@types/is-windows": ^1.0.2
  "@types/node": ^18.19.34
  "@types/normalize-path": ^3.0.2
  "@types/ramda": 0.29.12
  "@types/semver": 7.5.3
  "@types/sinon": ^10.0.20
  "@types/ssri": ^7.1.5
  "@types/zkochan__table": npm:@types/table@6.0.0
  "@types/which": ^2.0.2
  "@yarnpkg/core": 4.0.3
  "@zkochan/cmd-shim": ^6.0.0
  "@zkochan/retry": ^0.2.0
  "@zkochan/rimraf": ^2.1.3
  "@zkochan/table": ^2.0.1
  adm-zip: ^0.5.14
  better-path-resolve: 1.0.0
  camelcase: ^6.3.0
  camelcase-keys: ^6.2.2
  chalk: ^4.1.2
  ci-info: ^3.9.0
  cross-spawn: ^7.0.3
  enquirer: ^2.4.1
  execa: npm:safe-execa@0.1.2
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  graceful-fs: ^4.2.11
  is-subdir: ^1.2.0
  is-windows: ^1.0.2
  load-json-file: ^6.2.0
  make-empty-dir: ^2.1.0
  mem: ^8.1.1
  nock: 13.3.4
  node-fetch: npm:@pnpm/node-fetch@1.0.0
  normalize-path: ^3.0.0
  p-every: ^2.0.0
  p-filter: ^2.1.0
  p-limit: ^3.1.0
  path-absolute: ^1.0.1
  path-exists: ^4.0.0
  path-name: ^1.0.0
  ramda: npm:@pnpm/ramda@0.28.1
  read-ini-file: 4.0.0
  read-yaml-file: ^2.1.0
  realpath-missing: ^1.1.0
  rename-overwrite: ^5.0.0
  render-help: ^1.0.3
  run-groups: ^3.0.1
  semver: ^7.6.2
  sinon: ^16.1.3
  sort-keys: ^4.2.0
  ssri: 10.0.5
  strip-ansi: ^6.0.1
  strip-bom: ^4.0.0
  symlink-dir: ^6.0.0
  tempy: ^1.0.1
  version-selector-type: ^3.0.0
  which: npm:@pnpm/which@^3.0.1
  write-file-atomic: ^5.0.1
  write-json-file: ^4.3.0
  write-yaml-file: ^5.0.0
  write-pkg: 4.0.0
  yaml-tag: 1.1.0
