use_small_heuristics = "Default"

chain_complexity_layout = true
struct_lit_width = 0
struct_pattern_width = 35

# Use field initialize shorthand if possible
use_field_init_shorthand = true

# All unstable features that we wish for
# unstable_features = true
# version = "Two"
# Provide a cleaner impl order
# reorder_impl_items = true
# Provide a cleaner import sort order
# group_imports = "StdExternalCrate"
# Group "use" statements by crate
# imports_granularity = "Crate"
