const fs = require('fs')
console.log('Creating a tree of empty directories...')
fs.mkdirSync('empty-dirs/a/a/', { recursive: true })
fs.mkdirSync('empty-dirs/a/b/', { recursive: true })
fs.mkdirSync('empty-dirs/b/a/', { recursive: true })
fs.mkdirSync('empty-dirs/b/b/', { recursive: true })
console.log('Creating a tree of real files...')
fs.mkdirSync('files/foo/foo/', { recursive: true })
fs.writeFileSync('files/foo/foo/foo.txt', '')
fs.writeFileSync('files/foo/bar.txt', '')
fs.writeFileSync('files/foo_bar.txt', 'This is foo_bar')
console.log('Creating symlinks...')
fs.symlinkSync('files/foo_bar.txt', 'link-to-a-file', 'file')
fs.symlinkSync('files/foo', 'link-to-a-dir', 'dir')
