[package]
name                 = "pnpm-publish"
description          = "Publish a package to an npm registry (the `pnpm publish` command)"
version              = "0.0.1"
publish              = false
authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

[dependencies]
pnpm-diagnostics                       = { workspace = true }
pnpm-executor                          = { workspace = true }
pnpm-git-utils                         = { workspace = true }
pnpm-network                           = { workspace = true }
pnpm-network-web-auth                  = { workspace = true }
pnpm-pack                              = { workspace = true }
pnpm-package-manifest                  = { workspace = true }
pnpm-reporter                          = { workspace = true }
pnpm-resolving-parse-wanted-dependency = { workspace = true }

base64        = { workspace = true }
bytes         = { workspace = true }
derive_more   = { workspace = true }
dialoguer     = { workspace = true }
flate2        = { workspace = true }
miette        = { workspace = true }
node-semver   = { workspace = true }
pipe-trait    = { workspace = true }
reqwest       = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
sha2          = { workspace = true }
sigstore-sign = { workspace = true }
ssri          = { workspace = true }
tar           = { workspace = true }
tokio         = { workspace = true, features = ["time"] }
tracing       = { workspace = true }
url           = { workspace = true }

[dev-dependencies]
pnpm-network-web-auth-testing = { workspace = true }

mockito           = { workspace = true }
pretty_assertions = { workspace = true }
tempfile          = { workspace = true }
tokio             = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[lints]
workspace = true
