//! Human-readable random ids for intent files, in the adjective-noun-verb
//! shape the changesets ecosystem uses (`wild-wombats-do`). The exact word
//! pool is not part of the cross-stack contract — any collision-free file
//! name works — so a compact embedded list stands in for the TypeScript
//! side's `human-id` dependency.

const ADJECTIVES: &[&str] = &[
    "afraid", "ancient", "angry", "big", "brave", "breezy", "bright", "calm", "chilly", "clean",
    "clever", "cool", "curly", "curvy", "dry", "eager", "early", "empty", "fair", "famous", "fast",
    "fluffy", "fresh", "friendly", "funny", "gentle", "giant", "good", "great", "happy", "heavy",
    "honest", "hungry", "itchy", "khaki", "kind", "large", "lazy", "light", "little", "loud",
    "lucky", "mean", "mighty", "modern", "neat", "new", "nice", "old", "olive", "orange", "polite",
    "pretty", "proud", "purple", "quick", "quiet", "rare", "real", "shaggy", "sharp", "shiny",
    "short", "silent", "silly", "slow", "small", "smart", "smooth", "soft", "sour", "spicy",
    "strong", "sweet", "tall", "tame", "thick", "thin", "tidy", "tiny", "tough", "vast", "warm",
    "weak", "wet", "wicked", "wide", "wild", "wise", "young",
];

const NOUNS: &[&str] = &[
    "ants",
    "apes",
    "bats",
    "beans",
    "bears",
    "beds",
    "bees",
    "birds",
    "boats",
    "books",
    "bottles",
    "boxes",
    "buses",
    "camels",
    "carrots",
    "cats",
    "chairs",
    "cherries",
    "clocks",
    "clouds",
    "cobras",
    "cooks",
    "cows",
    "crabs",
    "cups",
    "deers",
    "dodos",
    "dogs",
    "dolphins",
    "donkeys",
    "doors",
    "dragons",
    "ducks",
    "eagles",
    "eels",
    "eggs",
    "elephants",
    "emus",
    "falcons",
    "fireants",
    "fishes",
    "flies",
    "flowers",
    "forks",
    "foxes",
    "frogs",
    "geckos",
    "geese",
    "goats",
    "grapes",
    "hairs",
    "hats",
    "horses",
    "hounds",
    "houses",
    "icons",
    "insects",
    "jars",
    "jeans",
    "jobs",
    "jokes",
    "keys",
    "kids",
    "kings",
    "kiwis",
    "knives",
    "lamps",
    "lemons",
    "lions",
    "lizards",
    "mails",
    "mangos",
    "maps",
    "melons",
    "mice",
    "moles",
    "monkeys",
    "moons",
    "moose",
    "mugs",
    "olives",
    "onions",
    "owls",
    "pandas",
    "peaches",
    "pears",
    "pens",
    "pigs",
    "planes",
    "plums",
    "poets",
    "pots",
    "pumas",
    "queens",
    "rabbits",
    "rats",
    "ravens",
    "rice",
    "rings",
    "rivers",
    "rocks",
    "roses",
    "seals",
    "seas",
    "sheep",
    "shirts",
    "shoes",
    "snails",
    "snakes",
    "socks",
    "spiders",
    "spoons",
    "squids",
    "stars",
    "suns",
    "swans",
    "tables",
    "taxis",
    "teeth",
    "tigers",
    "tips",
    "tools",
    "toys",
    "trains",
    "trees",
    "turkeys",
    "turtles",
    "walls",
    "wasps",
    "waves",
    "wolves",
    "wombats",
    "worms",
    "zebras",
];

const VERBS: &[&str] = &[
    "act", "add", "agree", "argue", "arrive", "ask", "attack", "bake", "bathe", "beam", "beg",
    "begin", "behave", "bet", "boil", "bow", "brake", "brush", "build", "burn", "buy", "call",
    "camp", "care", "carry", "change", "cheat", "cheer", "chew", "clap", "clean", "collect",
    "compare", "compete", "complain", "cough", "count", "cover", "crash", "cross", "cry", "dance",
    "decide", "deliver", "deny", "design", "destroy", "dig", "divide", "do", "double", "doubt",
    "draw", "dream", "dress", "drive", "drop", "drum", "eat", "end", "enjoy", "exist", "explain",
    "explode", "fail", "fetch", "film", "fix", "flash", "float", "flow", "fly", "fold", "fry",
    "give", "glow", "greet", "grin", "grow", "guess", "hammer", "hang", "happen", "heal", "hear",
    "help", "hide", "hope", "hug", "hunt", "invent", "invite", "itch", "jam", "jog", "join",
    "joke", "judge", "juggle", "jump", "kick", "kiss", "kneel", "knock", "know", "learn", "leave",
    "lick", "lie", "listen", "live", "look", "love", "march", "marry", "matter", "melt", "mix",
    "move", "nail", "notice", "obey", "occur", "open", "own", "pay", "peel", "perform", "play",
    "poke", "press", "pretend", "promise", "pull", "pump", "punch", "push", "raise", "reflect",
    "refuse", "relate", "relax", "remain", "remember", "repair", "repeat", "reply", "report",
    "rescue", "rest", "retire", "return", "rhyme", "ring", "roll", "rule", "run", "rush", "scream",
    "search", "sell", "serve", "shake", "share", "shave", "shine", "shop", "shout", "sin", "sing",
    "sip", "sit", "sleep", "smash", "smell", "smile", "smoke", "sneeze", "sniff", "sort", "speak",
    "stand", "stare", "start", "stay", "study", "swim", "switch", "tan", "tap", "taste", "teach",
    "tease", "tell", "thank", "think", "throw", "tickle", "tie", "trade", "train", "travel", "try",
    "turn", "type", "unite", "vanish", "visit", "wait", "walk", "warn", "wash", "watch", "wave",
    "whisper", "win", "wink", "wonder", "work", "worry", "yawn", "yell",
];

/// A random `adjective-nouns-verb` id, e.g. `wild-wombats-do`.
pub fn random_human_id() -> String {
    format!("{}-{}-{}", pick(ADJECTIVES), pick(NOUNS), pick(VERBS))
}

fn pick(words: &[&'static str]) -> &'static str {
    let mut buf = [0u8; 4];
    getrandom::fill(&mut buf).expect("read entropy from the operating system");
    words[u32::from_le_bytes(buf) as usize % words.len()]
}
