//! `pnpm import`, which generates `pnpm-lock.yaml` from another package
//! manager's lockfile. Ports the TypeScript CLI's `import` and
//! `importRecursive` tests.
//!
//! Every test asserts on the version the generated lockfile pins, not
//! just on the package being present: `import` has to keep what the
//! source lockfile resolved, so a version that plain resolution would
//! have picked instead is the regression these guard against.

use crate::_utils::{append_workspace_yaml_key, lockfile_package_keys};

use assert_cmd::prelude::*;
use command_extra::CommandExtra;
use pnpm_testing_utils::bin::{AddMockedRegistry, CommandTempCwd};
use std::{fs, path::Path};

const DEP_OF_PKG_WITH_1_DEP: &str = "@pnpm.e2e/dep-of-pkg-with-1-dep";

/// The manifest shared by pnpm's `has-package-lock-json`,
/// `has-npm-shrinkwrap-json`, and `has-package-lock-v3-json` fixtures.
/// The failing `prepare` script proves `import` runs no lifecycle
/// scripts.
const NPM_FIXTURE_MANIFEST: &str = r#"{
  "name": "has-npm-lockfile",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/dep-of-pkg-with-1-dep": "^101.0.0",
    "@pnpm.e2e/pkg-with-1-dep": "*"
  },
  "scripts": {
    "prepare": "exit 1"
  }
}"#;

/// npm lockfile version 1: a nested `dependencies` tree.
const NPM_LOCKFILE_V1: &str = r#"{
  "name": "has-npm-lockfile",
  "version": "0.0.0",
  "lockfileVersion": 1,
  "dependencies": {
    "@pnpm.e2e/dep-of-pkg-with-1-dep": {
      "version": "101.0.0"
    },
    "@pnpm.e2e/pkg-with-1-dep": {
      "version": "100.0.0",
      "dependencies": {
        "@pnpm.e2e/dep-of-pkg-with-1-dep": {
          "version": "100.0.0"
        }
      }
    }
  }
}"#;

/// npm lockfile version 3: a flat `packages` map. The nested
/// `100.0.0` of `@pnpm.e2e/dep-of-pkg-with-1-dep` is only recorded as a
/// range on its parent's `dependencies`.
const NPM_LOCKFILE_V3: &str = r#"{
  "name": "has-npm-lockfile",
  "version": "0.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "version": "0.0.0",
      "dependencies": {
        "@pnpm.e2e/pkg-with-1-dep": "100.0.0"
      }
    },
    "node_modules/@pnpm.e2e/dep-of-pkg-with-1-dep": {
      "version": "101.0.0"
    },
    "node_modules/@pnpm.e2e/pkg-with-1-dep": {
      "version": "100.0.0",
      "dependencies": {
        "@pnpm.e2e/dep-of-pkg-with-1-dep": "100.0.0"
      }
    }
  }
}"#;

const YARN_FIXTURE_MANIFEST: &str = r#"{
  "name": "has-yarn-lock",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/dep-of-pkg-with-1-dep": "^100.0.0",
    "@pnpm.e2e/pkg-with-1-dep": "*"
  }
}"#;

const YARN_CLASSIC_LOCKFILE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@pnpm.e2e/dep-of-pkg-with-1-dep@^100.0.0":
  version "100.0.0"
  resolved "http://localhost:7769/@pnpm.e2e%2fdep-of-pkg-with-1-dep/-/dep-of-pkg-with-1-dep-100.0.0.tgz#a95f834b4a4d9661623a0cf2bd76acbc213192fc"
  integrity sha512-KUmwlEiE3pzpmPCfrLkoOO7fmL4Tft+dcm6YQlUfOUJvHO73xlcKVoA/xOHP/ayUO8GiPlIqWRbKHrsxvXGE8g==

"@pnpm.e2e/pkg-with-1-dep@*":
  version "100.0.0"
  resolved "http://localhost:7769/@pnpm.e2e%2fpkg-with-1-dep/-/pkg-with-1-dep-100.0.0.tgz#2845d276feb3153c4abc107728ddbe0f7ce75a45"
  integrity sha512-tZBohBD7WeOtm0hBUQl0FlPvuTwyrdSn2V45P4jd2arjwKxM5YULEAtD1J42bKuEOJls4vS4/1v3lgS8qTfA2Q==
  dependencies:
    "@pnpm.e2e/dep-of-pkg-with-1-dep" "^100.0.0"
"#;

const YARN_BERRY_FIXTURE_MANIFEST: &str = r#"{
  "name": "has-yarn2-lock",
  "version": "0.0.0",
  "dependencies": {
    "minimatch": "^3.0.4"
  },
  "devDependencies": {
    "is-positive": "1.0.0"
  },
  "optionalDependencies": {
    "is-negative": "1.0.0"
  }
}"#;

/// Yarn berry's YAML format. The `minimatch` entry is keyed by two
/// descriptors at once, and `has-yarn2-lock@workspace:.` is the project
/// itself.
const YARN_BERRY_LOCKFILE: &str = r#"# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 5
  cacheKey: 8

"balanced-match@npm:^1.0.0":
  version: 1.0.2
  resolution: "balanced-match@npm:1.0.2"
  languageName: node
  linkType: hard

"brace-expansion@npm:^1.1.7":
  version: 1.1.11
  resolution: "brace-expansion@npm:1.1.11"
  dependencies:
    balanced-match: ^1.0.0
    concat-map: 0.0.1
  languageName: node
  linkType: hard

"concat-map@npm:0.0.1":
  version: 0.0.1
  resolution: "concat-map@npm:0.0.1"
  languageName: node
  linkType: hard

"has-yarn2-lock@workspace:.":
  version: 0.0.0-use.local
  resolution: "has-yarn2-lock@workspace:."
  dependencies:
    is-negative: 1.0.0
    is-positive: 1.0.0
    minimatch: ^3.0.4
  dependenciesMeta:
    is-negative:
      optional: true
  languageName: unknown
  linkType: soft

"is-negative@npm:1.0.0":
  version: 1.0.0
  resolution: "is-negative@npm:1.0.0"
  languageName: node
  linkType: hard

"is-positive@npm:1.0.0":
  version: 1.0.0
  resolution: "is-positive@npm:1.0.0"
  languageName: node
  linkType: hard

"minimatch@npm:2 || 3, minimatch@npm:^3.0.4":
  version: 3.0.4
  resolution: "minimatch@npm:3.0.4"
  dependencies:
    brace-expansion: ^1.1.7
  languageName: node
  linkType: hard
"#;

const WORKSPACE_ROOT_MANIFEST: &str = r#"{
  "private": true,
  "name": "workspace-has-shared-lockfile",
  "version": "1.0.0"
}"#;

const WORKSPACE_FOO_MANIFEST: &str = r#"{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "is-positive": "^1.0.0"
  }
}"#;

const WORKSPACE_BAR_MANIFEST: &str = r#"{
  "name": "bar",
  "version": "0.0.0",
  "dependencies": {
    "is-negative": "^1.0.0"
  }
}"#;

const WORKSPACE_YARN_LOCKFILE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


is-negative@^1.0.0:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/is-negative/-/is-negative-1.0.1.tgz#dc6b8728eebd03c75bf876087edcd50e9cb56994"
  integrity sha1-3GuHKO69A8db+HYIftzVDpy1aZQ=

is-positive@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/is-positive/-/is-positive-1.0.0.tgz#88009856b64a2f1eb7d8bb0179418424ae0452cb"
  integrity sha1-iACYVrZKLx632LsBeUGEJK4EUss=
"#;

/// npm lockfile version 2, which keeps both the flat `packages` map and
/// the nested `dependencies` tree. `import` reads the nested tree.
const WORKSPACE_NPM_LOCKFILE: &str = r#"{
  "name": "workspace-has-shared-lockfile",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "workspace-has-shared-lockfile",
      "version": "1.0.0",
      "workspaces": [
        "packages/**"
      ]
    },
    "node_modules/bar": {
      "resolved": "packages/bar",
      "link": true
    },
    "node_modules/foo": {
      "resolved": "packages/foo",
      "link": true
    },
    "node_modules/is-negative": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-negative/-/is-negative-1.0.1.tgz",
      "integrity": "sha1-3GuHKO69A8db+HYIftzVDpy1aZQ="
    },
    "node_modules/is-positive": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/is-positive/-/is-positive-1.0.0.tgz",
      "integrity": "sha1-iACYVrZKLx632LsBeUGEJK4EUss="
    },
    "packages/bar": {
      "version": "0.0.0",
      "dependencies": {
        "is-negative": "^1.0.0"
      }
    },
    "packages/foo": {
      "version": "0.0.0",
      "dependencies": {
        "is-positive": "^1.0.0"
      }
    }
  },
  "dependencies": {
    "bar": {
      "version": "file:packages/bar",
      "requires": {
        "is-negative": "^1.0.0"
      }
    },
    "foo": {
      "version": "file:packages/foo",
      "requires": {
        "is-positive": "^1.0.0"
      }
    },
    "is-negative": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-negative/-/is-negative-1.0.1.tgz",
      "integrity": "sha1-3GuHKO69A8db+HYIftzVDpy1aZQ="
    },
    "is-positive": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/is-positive/-/is-positive-1.0.0.tgz",
      "integrity": "sha1-iACYVrZKLx632LsBeUGEJK4EUss="
    }
  }
}"#;

fn write_file(dir: &Path, relative_path: &str, contents: &str) {
    let path = dir.join(relative_path);
    fs::create_dir_all(path.parent().expect("a file path has a parent"))
        .expect("create parent dir");
    fs::write(path, contents).expect("write fixture file");
}

fn assert_pins(workspace: &Path, expected: &[&str], rejected: &[&str]) {
    let packages = lockfile_package_keys(workspace);
    for key in expected {
        assert!(packages.contains(&(*key).to_string()), "{key} must be pinned, got {packages:?}");
    }
    for key in rejected {
        assert!(!packages.contains(&(*key).to_string()), "{key} must not be pinned");
    }
}

/// A workspace whose members declare the dependencies the shared foreign
/// lockfile pinned.
fn prepare_workspace(workspace: &Path) {
    append_workspace_yaml_key(workspace, "packages", r#"["packages/**"]"#);
    write_file(workspace, "package.json", WORKSPACE_ROOT_MANIFEST);
    write_file(workspace, "packages/foo/package.json", WORKSPACE_FOO_MANIFEST);
    write_file(workspace, "packages/bar/package.json", WORKSPACE_BAR_MANIFEST);
}

/// `is-positive` and `is-negative` come from the upstream registry, where
/// newer majors exist, so plain resolution of `^1.0.0` would pick
/// neither of these.
fn assert_workspace_pins(workspace: &Path) {
    assert_pins(workspace, &["is-positive@1.0.0", "is-negative@1.0.1"], &[]);
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");
}

#[test]
fn import_from_package_lock_json() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0", "@pnpm.e2e/pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_npm_shrinkwrap_json() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "npm-shrinkwrap.json", NPM_LOCKFILE_V1);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_package_lock_json_v3() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V3);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_yarn_lock() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", YARN_FIXTURE_MANIFEST);
    write_file(&workspace, "yarn.lock", YARN_CLASSIC_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0", "@pnpm.e2e/pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_yarn_berry_lock() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(&workspace, "package.json", YARN_BERRY_FIXTURE_MANIFEST);
    write_file(&workspace, "yarn.lock", YARN_BERRY_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    // `minimatch@3.0.4` is the pin the berry format hides behind an entry
    // keyed by two descriptors at once.
    assert_pins(&workspace, &["is-positive@1.0.0", "is-negative@1.0.0", "minimatch@3.0.4"], &[]);
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, mock_instance));
}

#[test]
fn import_fails_when_no_lockfile_is_found() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(&workspace, "package.json", r#"{"name":"project","version":"0.0.0"}"#);

    let output = pacquet.with_arg("import").output().expect("run import");
    assert!(!output.status.success(), "import must fail without a foreign lockfile");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("ERR_PNPM_LOCKFILE_NOT_FOUND"), "stderr:\n{stderr}");
    assert!(stderr.contains("No lockfile found"), "stderr:\n{stderr}");
    assert!(!workspace.join("pnpm-lock.yaml").exists(), "import must not write a lockfile");

    drop((root, mock_instance));
}

#[test]
fn import_replaces_existing_lockfile() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    write_file(&workspace, "pnpm-lock.yaml", "# stale placeholder lockfile\n");

    pacquet.with_arg("import").assert().success();

    let lockfile_path = workspace.join("pnpm-lock.yaml");
    let lockfile = fs::read_to_string(&lockfile_path).expect("read pnpm-lock.yaml");
    assert!(
        !lockfile.contains("stale placeholder lockfile"),
        "import must replace the old lockfile content",
    );
    assert_pins(&workspace, &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"], &[]);

    drop((root, npmrc_info));
}

#[test]
fn import_from_shared_yarn_lock_of_monorepo() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    prepare_workspace(&workspace);
    write_file(&workspace, "yarn.lock", WORKSPACE_YARN_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_workspace_pins(&workspace);

    drop((root, mock_instance));
}

#[test]
fn import_from_shared_package_lock_json_of_monorepo() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    prepare_workspace(&workspace);
    write_file(&workspace, "package-lock.json", WORKSPACE_NPM_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_workspace_pins(&workspace);

    drop((root, mock_instance));
}

#[test]
fn import_from_shared_npm_shrinkwrap_json_of_monorepo() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    prepare_workspace(&workspace);
    write_file(&workspace, "npm-shrinkwrap.json", WORKSPACE_NPM_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_workspace_pins(&workspace);

    drop((root, mock_instance));
}
