//! `pnpm import`, which generates `pnpm-lock.yaml` from another package
//! manager's lockfile. Ports the TypeScript CLI's `import` and
//! `importRecursive` tests.
//!
//! Every fixture pins a version that plain resolution of the same range
//! would not pick, and every assertion names both the version the source
//! lockfile recorded and the one resolution would have chosen instead.
//! Asserting only that a package is present would pass without the fix.
//!
//! The fixtures resolve against `@pnpm.e2e` packages, which the mocked
//! registry serves from local storage. Packages it proxies to the npm
//! upstream would make these tests depend on the network and on versions
//! published after they were written.

use crate::_utils::{append_workspace_yaml_key, lockfile_package_keys};

use assert_cmd::prelude::*;
use command_extra::CommandExtra;
use pnpm_testing_utils::bin::{AddMockedRegistry, CommandTempCwd};
use std::{fs, path::Path};

fn assert_no_import_backups(lockfile_dir: &Path) {
    let leftovers: Vec<_> = fs::read_dir(lockfile_dir)
        .expect("read the lockfile directory")
        .map(|entry| entry.expect("read a lockfile directory entry").file_name())
        .filter(|name| name.to_string_lossy().ends_with(".import.bak"))
        .collect();
    assert!(leftovers.is_empty(), "import backups left behind: {leftovers:?}");
}

const DEP_OF_PKG_WITH_1_DEP: &str = "@pnpm.e2e/dep-of-pkg-with-1-dep";

/// The manifest shared by pnpm's `has-package-lock-json`,
/// `has-npm-shrinkwrap-json`, and `has-package-lock-v3-json` fixtures.
/// The failing `prepare` script proves `import` runs no lifecycle
/// scripts.
const NPM_FIXTURE_MANIFEST: &str = r#"{
  "name": "has-npm-lockfile",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/dep-of-pkg-with-1-dep": "^101.0.0",
    "@pnpm.e2e/pkg-with-1-dep": "*"
  },
  "scripts": {
    "prepare": "exit 1"
  }
}"#;

/// npm lockfile version 1: a nested `dependencies` tree.
const NPM_LOCKFILE_V1: &str = r#"{
  "name": "has-npm-lockfile",
  "version": "0.0.0",
  "lockfileVersion": 1,
  "dependencies": {
    "@pnpm.e2e/dep-of-pkg-with-1-dep": {
      "version": "101.0.0"
    },
    "@pnpm.e2e/pkg-with-1-dep": {
      "version": "100.0.0",
      "dependencies": {
        "@pnpm.e2e/dep-of-pkg-with-1-dep": {
          "version": "100.0.0"
        }
      }
    }
  }
}"#;

/// npm lockfile version 3: a flat `packages` map. The nested
/// `100.0.0` of `@pnpm.e2e/dep-of-pkg-with-1-dep` is only recorded as a
/// range on its parent's `dependencies`.
const NPM_LOCKFILE_V3: &str = r#"{
  "name": "has-npm-lockfile",
  "version": "0.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "version": "0.0.0",
      "dependencies": {
        "@pnpm.e2e/pkg-with-1-dep": "100.0.0"
      }
    },
    "node_modules/@pnpm.e2e/dep-of-pkg-with-1-dep": {
      "version": "101.0.0"
    },
    "node_modules/@pnpm.e2e/pkg-with-1-dep": {
      "version": "100.0.0",
      "dependencies": {
        "@pnpm.e2e/dep-of-pkg-with-1-dep": "100.0.0"
      }
    }
  }
}"#;

const YARN_FIXTURE_MANIFEST: &str = r#"{
  "name": "has-yarn-lock",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/dep-of-pkg-with-1-dep": "^100.0.0",
    "@pnpm.e2e/pkg-with-1-dep": "*"
  }
}"#;

const YARN_CLASSIC_LOCKFILE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@pnpm.e2e/dep-of-pkg-with-1-dep@^100.0.0":
  version "100.0.0"
  resolved "http://localhost:7769/@pnpm.e2e%2fdep-of-pkg-with-1-dep/-/dep-of-pkg-with-1-dep-100.0.0.tgz#a95f834b4a4d9661623a0cf2bd76acbc213192fc"
  integrity sha512-KUmwlEiE3pzpmPCfrLkoOO7fmL4Tft+dcm6YQlUfOUJvHO73xlcKVoA/xOHP/ayUO8GiPlIqWRbKHrsxvXGE8g==

"@pnpm.e2e/pkg-with-1-dep@*":
  version "100.0.0"
  resolved "http://localhost:7769/@pnpm.e2e%2fpkg-with-1-dep/-/pkg-with-1-dep-100.0.0.tgz#2845d276feb3153c4abc107728ddbe0f7ce75a45"
  integrity sha512-tZBohBD7WeOtm0hBUQl0FlPvuTwyrdSn2V45P4jd2arjwKxM5YULEAtD1J42bKuEOJls4vS4/1v3lgS8qTfA2Q==
  dependencies:
    "@pnpm.e2e/dep-of-pkg-with-1-dep" "^100.0.0"
"#;

const YARN_BERRY_FIXTURE_MANIFEST: &str = r#"{
  "name": "has-yarn2-lock",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/pkg-with-1-dep": "^100.0.0",
    "@pnpm.e2e/foo": "^1.0.0"
  },
  "devDependencies": {
    "@pnpm.e2e/multi-version-a": "^1.0.0"
  },
  "optionalDependencies": {
    "@pnpm.e2e/bravo-dep": "^1.0.0"
  }
}"#;

/// Yarn berry's YAML format. The `@pnpm.e2e/foo` entry is keyed by two
/// descriptors at once, `@pnpm.e2e/dep-of-pkg-with-1-dep` is reachable
/// only as a transitive dependency, and `has-yarn2-lock@workspace:.` is
/// the project itself.
const YARN_BERRY_LOCKFILE: &str = r#"# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 5
  cacheKey: 8

"@pnpm.e2e/bravo-dep@npm:^1.0.0":
  version: 1.0.1
  resolution: "@pnpm.e2e/bravo-dep@npm:1.0.1"
  languageName: node
  linkType: hard

"@pnpm.e2e/dep-of-pkg-with-1-dep@npm:^100.0.0":
  version: 100.0.0
  resolution: "@pnpm.e2e/dep-of-pkg-with-1-dep@npm:100.0.0"
  languageName: node
  linkType: hard

"@pnpm.e2e/foo@npm:1 || 2, @pnpm.e2e/foo@npm:^1.0.0":
  version: 1.0.0
  resolution: "@pnpm.e2e/foo@npm:1.0.0"
  languageName: node
  linkType: hard

"@pnpm.e2e/multi-version-a@npm:^1.0.0":
  version: 1.0.0
  resolution: "@pnpm.e2e/multi-version-a@npm:1.0.0"
  languageName: node
  linkType: hard

"@pnpm.e2e/pkg-with-1-dep@npm:^100.0.0":
  version: 100.0.0
  resolution: "@pnpm.e2e/pkg-with-1-dep@npm:100.0.0"
  dependencies:
    "@pnpm.e2e/dep-of-pkg-with-1-dep": ^100.0.0
  languageName: node
  linkType: hard

"has-yarn2-lock@workspace:.":
  version: 0.0.0-use.local
  resolution: "has-yarn2-lock@workspace:."
  dependencies:
    "@pnpm.e2e/bravo-dep": ^1.0.0
    "@pnpm.e2e/foo": ^1.0.0
    "@pnpm.e2e/multi-version-a": ^1.0.0
    "@pnpm.e2e/pkg-with-1-dep": ^100.0.0
  dependenciesMeta:
    "@pnpm.e2e/bravo-dep":
      optional: true
  languageName: unknown
  linkType: soft
"#;

const WORKSPACE_ROOT_MANIFEST: &str = r#"{
  "private": true,
  "name": "workspace-has-shared-lockfile",
  "version": "1.0.0"
}"#;

const WORKSPACE_FOO_MANIFEST: &str = r#"{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/foo": "^1.0.0"
  }
}"#;

const WORKSPACE_BAR_MANIFEST: &str = r#"{
  "name": "bar",
  "version": "0.0.0",
  "dependencies": {
    "@pnpm.e2e/bravo-dep": "^1.0.0"
  }
}"#;

const WORKSPACE_YARN_LOCKFILE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@pnpm.e2e/bravo-dep@^1.0.0":
  version "1.0.1"
  resolved "http://localhost/@pnpm.e2e%2fbravo-dep/-/bravo-dep-1.0.1.tgz#dc6b8728eebd"
  integrity sha512-3GuHKO69A8db+HYIftzVDpy1aZQ=

"@pnpm.e2e/foo@^1.0.0":
  version "1.0.0"
  resolved "http://localhost/@pnpm.e2e%2ffoo/-/foo-1.0.0.tgz#88009856b64a"
  integrity sha512-iACYVrZKLx632LsBeUGEJK4EUss=
"#;

/// npm lockfile version 2, which keeps both the flat `packages` map and
/// the nested `dependencies` tree. `import` reads the nested tree.
const WORKSPACE_NPM_LOCKFILE: &str = r#"{
  "name": "workspace-has-shared-lockfile",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "workspace-has-shared-lockfile",
      "version": "1.0.0",
      "workspaces": [
        "packages/**"
      ]
    },
    "node_modules/bar": {
      "resolved": "packages/bar",
      "link": true
    },
    "node_modules/foo": {
      "resolved": "packages/foo",
      "link": true
    },
    "node_modules/@pnpm.e2e/bravo-dep": {
      "version": "1.0.1",
      "resolved": "http://localhost/@pnpm.e2e/bravo-dep/-/bravo-dep-1.0.1.tgz",
      "integrity": "sha512-3GuHKO69A8db+HYIftzVDpy1aZQ="
    },
    "node_modules/@pnpm.e2e/foo": {
      "version": "1.0.0",
      "resolved": "http://localhost/@pnpm.e2e/foo/-/foo-1.0.0.tgz",
      "integrity": "sha512-iACYVrZKLx632LsBeUGEJK4EUss="
    },
    "packages/bar": {
      "version": "0.0.0",
      "dependencies": {
        "@pnpm.e2e/bravo-dep": "^1.0.0"
      }
    },
    "packages/foo": {
      "version": "0.0.0",
      "dependencies": {
        "@pnpm.e2e/foo": "^1.0.0"
      }
    }
  },
  "dependencies": {
    "bar": {
      "version": "file:packages/bar",
      "requires": {
        "@pnpm.e2e/bravo-dep": "^1.0.0"
      }
    },
    "foo": {
      "version": "file:packages/foo",
      "requires": {
        "@pnpm.e2e/foo": "^1.0.0"
      }
    },
    "@pnpm.e2e/bravo-dep": {
      "version": "1.0.1",
      "resolved": "http://localhost/@pnpm.e2e/bravo-dep/-/bravo-dep-1.0.1.tgz",
      "integrity": "sha512-3GuHKO69A8db+HYIftzVDpy1aZQ="
    },
    "@pnpm.e2e/foo": {
      "version": "1.0.0",
      "resolved": "http://localhost/@pnpm.e2e/foo/-/foo-1.0.0.tgz",
      "integrity": "sha512-iACYVrZKLx632LsBeUGEJK4EUss="
    }
  }
}"#;

fn write_file(dir: &Path, relative_path: &str, contents: &str) {
    let path = dir.join(relative_path);
    fs::create_dir_all(path.parent().expect("a file path has a parent"))
        .expect("create parent dir");
    fs::write(path, contents).expect("write fixture file");
}

fn assert_pins(workspace: &Path, expected: &[&str], rejected: &[&str]) {
    let packages = lockfile_package_keys(workspace);
    for key in expected {
        assert!(packages.contains(&(*key).to_string()), "{key} must be pinned, got {packages:?}");
    }
    for key in rejected {
        assert!(!packages.contains(&(*key).to_string()), "{key} must not be pinned");
    }
}

/// A workspace whose members declare the dependencies the shared foreign
/// lockfile pinned.
fn prepare_workspace(workspace: &Path) {
    append_workspace_yaml_key(workspace, "packages", r#"["packages/**"]"#);
    write_file(workspace, "package.json", WORKSPACE_ROOT_MANIFEST);
    write_file(workspace, "packages/foo/package.json", WORKSPACE_FOO_MANIFEST);
    write_file(workspace, "packages/bar/package.json", WORKSPACE_BAR_MANIFEST);
}

/// Both members declare `^1.0.0`, and both packages publish a higher
/// 1.x, so the pins the foreign lockfile recorded are not what plain
/// resolution of those ranges picks.
fn assert_workspace_pins(workspace: &Path) {
    assert_pins(
        workspace,
        &["@pnpm.e2e/foo@1.0.0", "@pnpm.e2e/bravo-dep@1.0.1"],
        &["@pnpm.e2e/foo@1.3.0", "@pnpm.e2e/bravo-dep@1.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");
}

#[test]
fn import_from_package_lock_json() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0", "@pnpm.e2e/pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_npm_shrinkwrap_json() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "npm-shrinkwrap.json", NPM_LOCKFILE_V1);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_package_lock_json_v3() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V3);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_yarn_lock() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", YARN_FIXTURE_MANIFEST);
    write_file(&workspace, "yarn.lock", YARN_CLASSIC_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0", "@pnpm.e2e/pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_from_yarn_berry_lock() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(&workspace, "package.json", YARN_BERRY_FIXTURE_MANIFEST);
    write_file(&workspace, "yarn.lock", YARN_BERRY_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        &workspace,
        &[
            "@pnpm.e2e/pkg-with-1-dep@100.0.0",
            "@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0",
            "@pnpm.e2e/foo@1.0.0",
            "@pnpm.e2e/multi-version-a@1.0.0",
            "@pnpm.e2e/bravo-dep@1.0.1",
        ],
        &[
            "@pnpm.e2e/pkg-with-1-dep@100.1.0",
            "@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0",
            "@pnpm.e2e/foo@1.3.0",
            "@pnpm.e2e/multi-version-a@1.0.1",
            "@pnpm.e2e/bravo-dep@1.1.0",
        ],
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, mock_instance));
}

#[test]
fn import_fails_when_no_lockfile_is_found() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(&workspace, "package.json", r#"{"name":"project","version":"0.0.0"}"#);

    let output = pacquet.with_arg("import").output().expect("run import");
    assert!(!output.status.success(), "import must fail without a foreign lockfile");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("ERR_PNPM_LOCKFILE_NOT_FOUND"), "stderr:\n{stderr}");
    assert!(stderr.contains("No lockfile found"), "stderr:\n{stderr}");
    assert!(!workspace.join("pnpm-lock.yaml").exists(), "import must not write a lockfile");

    drop((root, mock_instance));
}

#[test]
fn import_replaces_existing_lockfile() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    write_file(&workspace, "pnpm-lock.yaml", "# stale placeholder lockfile\n");

    pacquet.with_arg("import").assert().success();

    let lockfile_path = workspace.join("pnpm-lock.yaml");
    let lockfile = fs::read_to_string(&lockfile_path).expect("read pnpm-lock.yaml");
    assert!(
        !lockfile.contains("stale placeholder lockfile"),
        "import must replace the old lockfile content",
    );
    assert_pins(
        &workspace,
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );

    drop((root, npmrc_info));
}

#[test]
fn import_preserves_project_lockfile_with_external_lockfile_dir() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    append_workspace_yaml_key(&workspace, "lockfileDir", "..");
    let project_lockfile = "# project lockfile must stay unchanged\n";
    write_file(&workspace, "pnpm-lock.yaml", project_lockfile);

    pacquet.with_arg("import").assert().success();

    assert_pins(
        root.path(),
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"],
        &["@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"],
    );
    let lockfile = pnpm_lockfile::Lockfile::load_wanted_from_dir(root.path())
        .expect("load imported lockfile")
        .expect("imported lockfile exists");
    assert_eq!(lockfile.importers.into_keys().collect::<Vec<_>>(), ["workspace"]);
    assert_eq!(
        fs::read_to_string(workspace.join("pnpm-lock.yaml")).expect("read project lockfile"),
        project_lockfile,
    );
    assert!(!workspace.join("node_modules").exists(), "import must not create node_modules");

    drop((root, npmrc_info));
}

#[test]
fn import_replaces_external_lockfile_and_preserves_its_env_document() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    write_file(root.path(), "pnpm-lock.yaml", "# stale placeholder lockfile\n");
    let mut env_lockfile = pnpm_lockfile::EnvLockfile::create();
    env_lockfile.root_importer_mut().config_dependencies.insert(
        "@pnpm.e2e/foo".to_string(),
        pnpm_lockfile::SpecifierAndResolution {
            specifier: "1.0.0".to_string(),
            version: "1.0.0".to_string(),
        },
    );
    env_lockfile.write(root.path()).expect("write external env document");
    append_workspace_yaml_key(&workspace, "lockfileDir", "..");

    pacquet.with_arg("import").assert().success();

    let lockfile = pnpm_lockfile::Lockfile::load_wanted_from_dir(root.path())
        .expect("load imported lockfile")
        .expect("imported lockfile exists");
    let packages: Vec<_> = lockfile
        .packages
        .expect("imported packages exist")
        .keys()
        .map(ToString::to_string)
        .collect();
    assert!(
        packages.contains(&"@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0".to_string()),
        "imported packages: {packages:?}",
    );
    assert!(
        !packages.contains(&"@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0".to_string()),
        "imported packages: {packages:?}",
    );
    assert_eq!(
        pnpm_lockfile::EnvLockfile::read(root.path()).expect("read external env document"),
        Some(env_lockfile),
    );
    assert!(!workspace.join("pnpm-lock.yaml").exists(), "no lockfile in the project directory");
    assert_no_import_backups(root.path());

    drop((root, npmrc_info));
}

#[test]
fn import_preserves_shared_lockfile_when_writing_a_branch_lockfile() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry_with_own_storage();
    npmrc_info.set_dist_tag(DEP_OF_PKG_WITH_1_DEP, "100.1.0", "latest");

    write_file(&workspace, "package.json", NPM_FIXTURE_MANIFEST);
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    write_file(&workspace, ".git/HEAD", "ref: refs/heads/feature/import\n");
    append_workspace_yaml_key(&workspace, "lockfileDir", "..");
    append_workspace_yaml_key(&workspace, "gitBranchLockfile", true);
    let shared_lockfile = "# shared lockfile must stay unchanged\n";
    write_file(root.path(), "pnpm-lock.yaml", shared_lockfile);
    let mut env_lockfile = pnpm_lockfile::EnvLockfile::create();
    env_lockfile.root_importer_mut().config_dependencies.insert(
        "@pnpm.e2e/foo".to_string(),
        pnpm_lockfile::SpecifierAndResolution {
            specifier: "1.0.0".to_string(),
            version: "1.0.0".to_string(),
        },
    );
    env_lockfile.write(root.path()).expect("write shared env document");
    let shared_lockfile =
        fs::read_to_string(root.path().join("pnpm-lock.yaml")).expect("read shared lockfile");
    write_file(root.path(), "pnpm-lock.feature!import.yaml", "# stale branch lockfile\n");

    pacquet.with_arg("import").assert().success();

    let lockfile =
        pnpm_lockfile::Lockfile::load_from_path(&root.path().join("pnpm-lock.feature!import.yaml"))
            .expect("load branch lockfile")
            .expect("branch lockfile exists");
    assert_eq!(lockfile.importers.into_keys().collect::<Vec<_>>(), ["workspace"]);
    let packages = lockfile.packages.expect("imported packages exist");
    assert!(
        packages.keys().any(|key| key.to_string() == "@pnpm.e2e/dep-of-pkg-with-1-dep@100.0.0"),
    );
    assert!(
        !packages.keys().any(|key| key.to_string() == "@pnpm.e2e/dep-of-pkg-with-1-dep@100.1.0"),
    );
    assert_eq!(
        fs::read_to_string(root.path().join("pnpm-lock.yaml")).expect("read shared lockfile"),
        shared_lockfile,
    );
    assert_no_import_backups(root.path());

    drop((root, npmrc_info));
}

#[test]
fn failed_import_restores_branch_lockfile() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(
        &workspace,
        "package.json",
        r#"{"dependencies":{"@pnpm.e2e/hello-world-js-bin-parent":"99.99.99"}}"#,
    );
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    write_file(&workspace, ".git/HEAD", "ref: refs/heads/feature/import\n");
    append_workspace_yaml_key(&workspace, "lockfileDir", "..");
    append_workspace_yaml_key(&workspace, "gitBranchLockfile", true);
    let shared_lockfile = "# shared lockfile\n";
    let branch_lockfile = "# branch lockfile\n";
    write_file(root.path(), "pnpm-lock.yaml", shared_lockfile);
    write_file(root.path(), "pnpm-lock.feature!import.yaml", branch_lockfile);

    let output = pacquet.with_arg("import").assert().failure();
    let stderr = String::from_utf8_lossy(&output.get_output().stderr);
    assert!(stderr.contains("ERR_PNPM_NO_MATCHING_VERSION"), "stderr:\n{stderr}");
    assert_eq!(
        fs::read_to_string(root.path().join("pnpm-lock.feature!import.yaml"))
            .expect("read restored branch lockfile"),
        branch_lockfile,
    );
    assert_eq!(
        fs::read_to_string(root.path().join("pnpm-lock.yaml")).expect("read shared lockfile"),
        shared_lockfile,
    );
    assert_no_import_backups(root.path());

    drop((root, mock_instance));
}

#[test]
fn failed_import_restores_external_lockfile() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(
        &workspace,
        "package.json",
        r#"{"dependencies":{"@pnpm.e2e/hello-world-js-bin-parent":"99.99.99"}}"#,
    );
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    append_workspace_yaml_key(&workspace, "lockfileDir", "..");
    let original_lockfile = "# existing external lockfile\n";
    write_file(root.path(), "pnpm-lock.yaml", original_lockfile);

    let output = pacquet.with_arg("import").assert().failure();
    let stderr = String::from_utf8_lossy(&output.get_output().stderr);
    assert!(stderr.contains("ERR_PNPM_NO_MATCHING_VERSION"), "stderr:\n{stderr}");
    assert_eq!(
        fs::read_to_string(root.path().join("pnpm-lock.yaml")).expect("read restored lockfile"),
        original_lockfile,
    );
    assert_no_import_backups(root.path());
    assert!(!workspace.join("pnpm-lock.yaml").exists(), "no lockfile in the project directory");

    drop((root, mock_instance));
}

#[test]
fn failed_import_writes_no_lockfile_where_there_was_none() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    write_file(
        &workspace,
        "package.json",
        r#"{"dependencies":{"@pnpm.e2e/hello-world-js-bin-parent":"99.99.99"}}"#,
    );
    write_file(&workspace, "package-lock.json", NPM_LOCKFILE_V1);
    append_workspace_yaml_key(&workspace, "lockfileDir", "..");

    let output = pacquet.with_arg("import").assert().failure();
    let stderr = String::from_utf8_lossy(&output.get_output().stderr);
    assert!(stderr.contains("ERR_PNPM_NO_MATCHING_VERSION"), "stderr:\n{stderr}");
    assert!(
        !root.path().join("pnpm-lock.yaml").exists(),
        "no lockfile in the external lockfile directory",
    );
    assert_no_import_backups(root.path());
    assert!(!workspace.join("pnpm-lock.yaml").exists(), "no lockfile in the project directory");

    drop((root, mock_instance));
}

#[test]
fn import_from_shared_yarn_lock_of_monorepo() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    prepare_workspace(&workspace);
    write_file(&workspace, "yarn.lock", WORKSPACE_YARN_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_workspace_pins(&workspace);

    drop((root, mock_instance));
}

#[test]
fn import_from_shared_package_lock_json_of_monorepo() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    prepare_workspace(&workspace);
    write_file(&workspace, "package-lock.json", WORKSPACE_NPM_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_workspace_pins(&workspace);

    drop((root, mock_instance));
}

#[test]
fn import_from_shared_npm_shrinkwrap_json_of_monorepo() {
    let CommandTempCwd { pacquet, root, workspace, npmrc_info, .. } =
        CommandTempCwd::init().add_mocked_registry();
    let AddMockedRegistry { mock_instance, .. } = npmrc_info;

    prepare_workspace(&workspace);
    write_file(&workspace, "npm-shrinkwrap.json", WORKSPACE_NPM_LOCKFILE);

    pacquet.with_arg("import").assert().success();

    assert_workspace_pins(&workspace);

    drop((root, mock_instance));
}
