[package]
name = "pnpm-yaml-document-sync"
version = "0.0.1"
publish = false
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde_json = { workspace = true }
serde-saphyr = { workspace = true }
yaml_serde = { workspace = true }
yamlpatch = { workspace = true }
yamlpath = { workspace = true }

[lints]
workspace = true
