//! Pacquet port of pnpm's lockfile-verification gate.
//!
//! Runs every active [`ResolutionVerifier`] against every entry in a
//! lockfile loaded from disk, before any resolver decision or fetch
//! happens. A lockfile whose entries were resolved elsewhere
//! (committed to the repo, restored from CI cache, generated by a tool
//! that skipped local policy) cannot reach the install path under a
//! weaker or absent policy.
//!
//! Mirrors upstream pnpm at commit `2a9bd897bf`:
//!
//! - [`verifyLockfileResolutions.ts`](https://github.com/pnpm/pnpm/blob/2a9bd897bf/installing/deps-installer/src/install/verifyLockfileResolutions.ts)
//!   — the fan-out runner.
//! - [`verifyLockfileResolutionsCache.ts`](https://github.com/pnpm/pnpm/blob/2a9bd897bf/installing/deps-installer/src/install/verifyLockfileResolutionsCache.ts)
//!   — the JSONL stat-and-skip cache (lands in a follow-up slice).
//!
//! Public surface today: [`verify_lockfile_resolutions`],
//! [`collect_resolution_policy_violations`], [`hash_lockfile`], and
//! [`VerifyError`].
//!
//! [`ResolutionVerifier`]: pacquet_resolving_resolver_base::ResolutionVerifier

mod errors;
mod hash_lockfile;
mod verify_lockfile_resolutions;

pub use errors::VerifyError;
pub use hash_lockfile::hash_lockfile;
pub use verify_lockfile_resolutions::{
    VerifyLockfileResolutionsOptions, collect_resolution_policy_violations,
    verify_lockfile_resolutions,
};
