//! Pacquet port of pnpm's lockfile-verification gate.
//!
//! Runs every active [`ResolutionVerifier`] against every entry in a
//! lockfile loaded from disk, before any resolver decision or fetch
//! happens. A lockfile whose entries were resolved elsewhere
//! (committed to the repo, restored from CI cache, generated by a tool
//! that skipped local policy) cannot reach the install path under a
//! weaker or absent policy.
//!
//! Mirrors upstream pnpm at commit `2a9bd897bf`:
//!
//! - [`verifyLockfileResolutions.ts`](https://github.com/pnpm/pnpm/blob/2a9bd897bf/installing/deps-installer/src/install/verifyLockfileResolutions.ts)
//!   — the fan-out runner.
//! - [`verifyLockfileResolutionsCache.ts`](https://github.com/pnpm/pnpm/blob/2a9bd897bf/installing/deps-installer/src/install/verifyLockfileResolutionsCache.ts)
//!   — the JSONL stat-and-skip cache.
//!
//! Public surface today: [`verify_lockfile_resolutions()`],
//! [`collect_resolution_policy_violations()`], [`hash_lockfile()`],
//! [`VerifyError`], and [`RenderedViolation`] — the last lets a caller
//! that resolved violations out-of-process (e.g. the pnpr client
//! reconstructing them from the server's response) rebuild the same
//! [`VerifyError`] via [`VerifyError::from_rendered`].
//!
//! [`ResolutionVerifier`]: pacquet_resolving_resolver_base::ResolutionVerifier

mod cache;
mod errors;
mod hash_lockfile;
mod record_lockfile_verified;
mod verify_lockfile_resolutions;

pub use cache::{
    CACHE_FILE_NAME, COMPACT_TRIGGER_BYTES, CacheLockfile, CacheLookupResult, CachePrecomputed,
    CacheRecord, LockfileStat, MAX_CACHE_ENTRIES, record_verification,
    try_lockfile_verification_cache,
};
pub use errors::{RenderedViolation, VerifyError};
pub use hash_lockfile::hash_lockfile;
pub use record_lockfile_verified::record_lockfile_verified;
pub use verify_lockfile_resolutions::{
    RESOLUTION_SHAPE_MISMATCH_VIOLATION_CODE, VerifyLockfileResolutionsOptions,
    collect_resolution_policy_violations, verify_lockfile_resolutions,
};
