use pretty_assertions::assert_eq;

use crate::VersionsByPackageName;

use super::collect_yarn_lockfile_versions;

fn collect(contents: &str) -> Vec<(String, Vec<String>)> {
    let mut versions = VersionsByPackageName::new();
    collect_yarn_lockfile_versions(contents, &mut versions);
    versions.into_iter().map(|(name, versions)| (name, versions.into_iter().collect())).collect()
}

#[test]
fn yarn_classic() {
    let versions = collect(
        r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@pnpm.e2e/dep-of-pkg-with-1-dep@^100.0.0":
  version "100.0.0"
  resolved "http://localhost:4873/@pnpm.e2e%2fdep-of-pkg-with-1-dep/-/dep-of-pkg-with-1-dep-100.0.0.tgz"
  integrity sha512-deadbeef

"@pnpm.e2e/pkg-with-1-dep@*":
  version "100.0.0"
  resolved "http://localhost:4873/@pnpm.e2e%2fpkg-with-1-dep/-/pkg-with-1-dep-100.0.0.tgz"
  dependencies:
    "@pnpm.e2e/dep-of-pkg-with-1-dep" "^100.0.0"
"#,
    );
    assert_eq!(
        versions,
        vec![
            ("@pnpm.e2e/dep-of-pkg-with-1-dep".to_string(), vec!["100.0.0".to_string()]),
            ("@pnpm.e2e/pkg-with-1-dep".to_string(), vec!["100.0.0".to_string()]),
        ],
    );
}

#[test]
fn yarn_classic_entry_shared_by_several_descriptors() {
    let versions = collect(
        r#""@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.2.0"

minimatch@2 || 3, minimatch@^3.0.4:
  version "3.0.4"
"#,
    );
    assert_eq!(
        versions,
        vec![
            ("@babel/core".to_string(), vec!["7.2.0".to_string()]),
            ("minimatch".to_string(), vec!["3.0.4".to_string()]),
        ],
    );
}

#[test]
fn yarn_berry() {
    let versions = collect(
        r#"# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 5
  cacheKey: 8

"has-yarn2-lock@workspace:.":
  version: 0.0.0-use.local
  resolution: "has-yarn2-lock@workspace:."
  languageName: unknown
  linkType: soft

"minimatch@npm:2 || 3, minimatch@npm:^3.0.4":
  version: 3.0.4
  resolution: "minimatch@npm:3.0.4"
  dependencies:
    brace-expansion: ^1.1.7
  checksum: deadbeef
  languageName: node
  linkType: hard
"#,
    );
    assert_eq!(
        versions,
        vec![
            ("has-yarn2-lock".to_string(), vec!["0.0.0-use.local".to_string()]),
            ("minimatch".to_string(), vec!["3.0.4".to_string()]),
        ],
    );
}

#[test]
fn a_dependency_named_version_is_not_read_as_a_version() {
    let versions = collect(
        r#"depends-on-version@^1.0.0:
  version "1.0.0"
  dependencies:
    version "^2.0.0"
"#,
    );
    assert_eq!(versions, vec![("depends-on-version".to_string(), vec!["1.0.0".to_string()])]);
}

#[test]
fn an_empty_lockfile_yields_nothing() {
    assert!(collect("").is_empty());
    assert!(collect("__metadata:\n  version: 6\n").is_empty());
}
