use pretty_assertions::assert_eq;

use crate::VersionsByPackageName;

use super::{YarnSyntaxError, collect_yarn_lockfile_versions};

fn collect(contents: &str) -> Vec<(String, Vec<String>)> {
    let mut versions = VersionsByPackageName::new();
    collect_yarn_lockfile_versions(contents, &mut versions).expect("parse yarn.lock");
    versions.into_iter().map(|(name, versions)| (name, versions.into_iter().collect())).collect()
}

fn collect_err(contents: &str) -> YarnSyntaxError {
    let mut versions = VersionsByPackageName::new();
    collect_yarn_lockfile_versions(contents, &mut versions).expect_err("reject the yarn.lock")
}

#[test]
fn yarn_classic() {
    let versions = collect(
        r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@pnpm.e2e/dep-of-pkg-with-1-dep@^100.0.0":
  version "100.0.0"
  resolved "http://localhost:4873/@pnpm.e2e%2fdep-of-pkg-with-1-dep/-/dep-of-pkg-with-1-dep-100.0.0.tgz"
  integrity sha512-deadbeef

"@pnpm.e2e/pkg-with-1-dep@*":
  version "100.0.0"
  resolved "http://localhost:4873/@pnpm.e2e%2fpkg-with-1-dep/-/pkg-with-1-dep-100.0.0.tgz"
  dependencies:
    "@pnpm.e2e/dep-of-pkg-with-1-dep" "^100.0.0"
"#,
    );
    assert_eq!(
        versions,
        vec![
            ("@pnpm.e2e/dep-of-pkg-with-1-dep".to_string(), vec!["100.0.0".to_string()]),
            ("@pnpm.e2e/pkg-with-1-dep".to_string(), vec!["100.0.0".to_string()]),
        ],
    );
}

/// A `resolved` URL carries a `#` fragment, which must not be mistaken
/// for the start of a comment.
#[test]
fn a_url_fragment_is_not_a_comment() {
    let versions = collect(
        r#"is-positive@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/is-positive/-/is-positive-1.0.0.tgz#88009856b64a"
"#,
    );
    assert_eq!(versions, vec![("is-positive".to_string(), vec!["1.0.0".to_string()])]);
}

#[test]
fn yarn_classic_entry_shared_by_several_descriptors() {
    let versions = collect(
        r#""@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.2.0"

minimatch@2 || 3, minimatch@^3.0.4:
  version "3.0.4"
"#,
    );
    assert_eq!(
        versions,
        vec![
            ("@babel/core".to_string(), vec!["7.2.0".to_string()]),
            ("minimatch".to_string(), vec!["3.0.4".to_string()]),
        ],
    );
}

#[test]
fn yarn_berry() {
    let versions = collect(
        r#"# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 5
  cacheKey: 8

"has-yarn2-lock@workspace:.":
  version: 0.0.0-use.local
  resolution: "has-yarn2-lock@workspace:."
  languageName: unknown
  linkType: soft

"minimatch@npm:2 || 3, minimatch@npm:^3.0.4":
  version: 3.0.4
  resolution: "minimatch@npm:3.0.4"
  dependencies:
    brace-expansion: ^1.1.7
  checksum: deadbeef
  languageName: node
  linkType: hard
"#,
    );
    assert_eq!(
        versions,
        vec![
            ("has-yarn2-lock".to_string(), vec!["0.0.0-use.local".to_string()]),
            ("minimatch".to_string(), vec!["3.0.4".to_string()]),
        ],
    );
}

/// YAML types an unquoted `version: 3` as a number, so reading it as a
/// string would drop the pin.
#[test]
fn a_berry_version_that_looks_numeric_is_still_collected() {
    let versions = collect("__metadata:\n  version: 6\n\n\"whole@npm:3\":\n  version: 3\n");
    assert_eq!(versions, vec![("whole".to_string(), vec!["3".to_string()])]);
}

#[test]
fn a_dependency_named_version_is_not_read_as_a_version() {
    let versions = collect(
        r#"depends-on-version@^1.0.0:
  version "1.0.0"
  dependencies:
    version "^2.0.0"
"#,
    );
    assert_eq!(versions, vec![("depends-on-version".to_string(), vec!["1.0.0".to_string()])]);
}

/// Yarn writes a header-only lockfile for a project with no
/// dependencies, in both dialects. That is not a parse failure.
#[test]
fn a_lockfile_without_entries_is_valid_and_yields_nothing() {
    assert!(collect("").is_empty());
    assert!(collect("# yarn lockfile v1\n").is_empty());
    assert!(collect("__metadata:\n  version: 6\n").is_empty());
}

#[test]
fn a_classic_entry_key_without_a_colon_is_rejected() {
    let error = collect_err("is-positive@^1.0.0\n  version \"1.0.0\"\n");
    assert!(matches!(error, YarnSyntaxError::EntryKeyExpected { line: 1 }), "got {error}");
}

#[test]
fn a_property_before_any_entry_is_rejected() {
    let error = collect_err("# yarn lockfile v1\n  version \"1.0.0\"\n");
    assert!(matches!(error, YarnSyntaxError::OrphanedProperty { line: 2 }), "got {error}");
}

#[test]
fn a_valueless_classic_property_is_rejected() {
    let error = collect_err("is-positive@^1.0.0:\n  version\n");
    assert!(matches!(error, YarnSyntaxError::PropertyExpected { line: 2 }), "got {error}");
}

#[test]
fn a_berry_lockfile_that_is_not_valid_yaml_is_rejected() {
    let error = collect_err("__metadata:\n  version: 6\n \"unclosed: [\n");
    assert!(matches!(error, YarnSyntaxError::Yaml { .. }), "got {error}");
}

#[test]
fn a_berry_entry_that_is_not_a_mapping_is_rejected() {
    let error = collect_err("__metadata:\n  version: 6\n\"is-positive@npm:1.0.0\":\n  - 1\n");
    assert!(
        matches!(&error, YarnSyntaxError::BerryEntryNotAMapping { entry } if entry == "is-positive@npm:1.0.0"),
        "got {error}",
    );
}
