[package]
name                 = "pnpm-global"
description          = "Global package install support (ports @pnpm/global.packages and @pnpm/global.commands)"
version              = "0.0.1"
publish              = false
authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

[dependencies]
pnpm-cmd-shim                = { workspace = true }
pnpm-crypto-hash             = { workspace = true }
pnpm-fs                      = { workspace = true }
pnpm-package-manifest        = { workspace = true }
pnpm-resolving-deps-resolver = { workspace = true }

derive_more = { workspace = true }
miette      = { workspace = true }
owo-colors  = { workspace = true }
serde_json  = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(windows)'.dev-dependencies]
junction = { workspace = true }

[lints]
workspace = true
