[package]
name                  = "pnpm-resolving-default-resolver"
version               = "0.0.1"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
pnpm-config                       = { workspace = true }
pnpm-engine-pm-yarn-resolver      = { workspace = true }
pnpm-engine-runtime-bun-resolver  = { workspace = true }
pnpm-engine-runtime-deno-resolver = { workspace = true }
pnpm-engine-runtime-node-resolver = { workspace = true }
pnpm-network                      = { workspace = true }
pnpm-resolving-git-resolver       = { workspace = true }
pnpm-resolving-local-resolver     = { workspace = true }
pnpm-resolving-npm-resolver       = { workspace = true }
pnpm-resolving-resolver-base      = { workspace = true }
pnpm-resolving-tarball-resolver   = { workspace = true }

derive_more = { workspace = true }
miette      = { workspace = true }

[dev-dependencies]
pnpm-lockfile = { workspace = true }

ssri  = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
