//! The lockfile-verification gate.
//!
//! Runs every active [`ResolutionVerifier`] against every entry in a
//! lockfile loaded from disk, before any resolver decision or fetch
//! happens. A lockfile whose entries were resolved elsewhere
//! (committed to the repo, restored from CI cache, generated by a tool
//! that skipped local policy) cannot reach the install path under a
//! weaker or absent policy.
//!
//! This crate is built from two parts: the fan-out runner and the
//! JSONL stat-and-skip cache.
//!
//! [`ResolutionVerifier`]: pnpm_resolving_resolver_base::ResolutionVerifier

pub use cache::{
    CACHE_FILE_NAME, COMPACT_TRIGGER_BYTES, CacheLockfile, CacheLookupResult, CachePrecomputed,
    CacheRecord, LockfileStat, MAX_CACHE_ENTRIES, record_verification,
    try_lockfile_verification_cache,
};
pub use errors::{RenderedViolation, VerifyError};
pub use hash_lockfile::hash_lockfile;
pub use record_lockfile_verified::record_lockfile_verified;
pub use verify_lockfile_resolutions::{
    RESOLUTION_SHAPE_MISMATCH_VIOLATION_CODE, ReplacedEntries, VerifyLockfileResolutionsOptions,
    collect_resolution_policy_violations, lockfile_verification_is_cached,
    lockfile_verification_is_cached_by_content, verify_lockfile_dependency_names,
    verify_lockfile_importer_snapshot_links, verify_lockfile_resolutions,
};

mod cache;
mod errors;
mod hash_lockfile;
mod record_lockfile_verified;
mod verify_lockfile_resolutions;

#[cfg(target_family = "wasm")]
pub(crate) use pnpm_wasm_host::process_id;
#[cfg(not(target_family = "wasm"))]
pub(crate) use std::process::id as process_id;
