///<reference path="../../../typings/index.d.ts" />
import './add'
import './addRecursive'
import './linkRecursive'
import './miscRecursive'
import './prune'
import './remove/completion'
import './update/getUpdateChoices.test'
import './update/interactive'
import './update/recursive'
import './update/update'
import './updateWorkspaceDependencies.test'
