[package]
name = "pnpm-which"
description = "Native and WebContainer executable lookup for pnpm"
version = "0.0.1"
publish = false
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
which = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
pnpm-fs = { workspace = true }

[lints]
workspace = true
