#!/usr/bin/env sh
set -o errexit -o nounset

if command -v pnpm >/dev/null; then
  pnpm commitlint --edit --config=commitlint.config.cjs
else
  echo 'No pnpm command found. Skip linting commit message.' >&2
fi
