#! /usr/bin/env sh
set -o errexit -o nounset

runner=$(
  command -v pnpm ||
  command -v npm ||
  true
)

if [ -n "$runner" ]; then
  exec "$runner" run lint --quiet
else
  echo 'Neither pnpm nor npm was found. Skip linting.' >&2
fi
