scripts:
  prepareFixtures: >
    node ../packages/pnpm/dist/pnpm.cjs install -rf --frozen-lockfile --no-shared-workspace-lockfile --no-link-workspace-packages &&
    node ../packages/pnpm/dist/pnpm.cjs install -rf -C fixtureWithLinks --frozen-lockfile --link-workspace-packages --no-shared-workspace-lockfile &&
    cd ./fixture-with-external-shrinkwrap/pkg && node ../../../packages/pnpm/dist/pnpm.cjs install -f --frozen-lockfile
