packages:
  - '*'
  - '!fixtureWithLinks'
  - '!has-major-outdated-deps'
  - '!has-no-lockfile'
  - '!has-not-outdated-deps'
  - '!has-npm-shrinkwrap-json'
  - '!has-only-deprecated-deps'
  - '!has-outdated-deps'
  - '!has-package-lock-json'
  - '!has-package-lock-v3-json'
  - '!hello-world-js-bin'
  - '!has-yarn-lock'
  - '!has-yarn2-lock'
  - '!workspace-with-lockfile-dupes'
  - '!workspace-with-lockfile-subdep-dupes'
  - '!workspace-has-shared-yarn-lock'
  - '!workspace-has-shared-package-lock-json'
  - '!workspace-has-shared-npm-shrinkwrap-json'
sharedWorkspaceLockfile: false

catalog:
  # Used in has-outdated-deps-using-catalog-protocol fixture.
  is-negative: ^1.0.0
