[package]
name                 = "pnpr-pypi"
version              = "0.0.1"
description          = "The Python Simple Repository API (PEP 503 / PEP 691) and legacy upload API pieces pnpr speaks"
publish              = false
authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license-file         = "../../LICENSE.md"
repository.workspace = true

[dependencies]
pnpm-network = { workspace = true }
derive_more  = { workspace = true }
pep440_rs    = { workspace = true }
pep508_rs    = { workspace = true }
regex        = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }

[lints]
workspace = true
