name: Audit

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install pnpm
      uses: pnpm/action-setup@994d756a33d64d79175a2d721a1a1b6976958b2d
      with:
        standalone: true
    - name: Audit
      run: pnpm audit
