name: Audit

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install pnpm
      uses: pnpm/action-setup@58e6119fe4f3092a76a7771efb55e04d25b6b26f
      with:
        standalone: true
    - name: Audit
      run: pnpm audit
