name: Audit

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Install pnpm
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      with:
        standalone: true
    - name: Audit
      run: pnpm audit
