# Run `cargo-unused-features` for finding out unused features
# NOTE: this is broken for now, see https://github.com/TimonPost/cargo-unused-features/pull/10

name: Pacquet Cargo Unused Features

permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bloat:
    name: Cargo Unused Features
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup

      - name: Install cargo-unused-features
        uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2.83.4
        with:
          tool: cargo-unused-features

      - name: Run
        run: unused-features analyze

  check-dependencies:
    name: Check Unused Dependencies
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            src:
              - 'Cargo.lock'

      - name: Install cargo-udeps
        if: steps.filter.outputs.src == 'true'
        uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2.83.4
        with:
          tool: cargo-udeps

      - if: steps.filter.outputs.src == 'true'
        run: cargo udeps
