# Run `cargo-unused-features` for finding out unused features
# NOTE: this is broken for now, see https://github.com/TimonPost/cargo-unused-features/pull/10

name: Pacquet Cargo Unused Features

permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bloat:
    name: Cargo Unused Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup

      - name: Install cargo-unused-features
        uses: taiki-e/install-action@e1c4cd42111751368541a7cb5db3522bd1f846a4 # v2.78.0
        with:
          tool: cargo-unused-features

      - name: Run
        run: unused-features analyze

  check-dependencies:
    name: Check Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            src:
              - 'Cargo.lock'

      - name: Install cargo-udeps
        if: steps.filter.outputs.src == 'true'
        uses: taiki-e/install-action@e1c4cd42111751368541a7cb5db3522bd1f846a4 # v2.78.0
        with:
          tool: cargo-udeps

      - if: steps.filter.outputs.src == 'true'
        run: cargo udeps
